= English Book
Doc Writer <vojtehovsky@gmail.com>
2014-12-08
:revnumber: {project-version}
:toc:
:toc-title: Content

:numbered:
== Артикль

include::articles/article.adoc[]

:numbered:
== Существительное

include::articles/nouns.adoc[]

:numbered:
== Прилагательное

Прилагательные не изменяются ни в роде, ни в числе.

:numbered:
== Местоимения

include::articles/pronouns.adoc[]

:numbered:
== Глагол

Настоящее неопределенное время (*_The Present Indefinite Tense_*) употребляется для обозначения обычного действия или
состояния предмета, а также повторяющихся действий. Спряжение глагола в этом времени очень просто. Все формы кроме единственного числа 3-го лица (имеющего окончание `-s`) совпадают с словарной. Например:

====
I take +
he (she, it) takes +
we take +
you take +
they take +
====

=== Модальные глаголы (can, may, must)

include::articles/modal_verbs.adoc[]

=== Вопросительная форма глаголов

include::articles/interrogative.adoc[]

=== Отрицательная форма глагола

include::articles/negative_verbs.adoc[]

=== Инфинитив

Инфинитивом, или неопределенным наклонением глагола, называется та его форма, которая отвечает на вопрос: *что делать? что сделать?* Признаком инфинитива в английском языке является частица `to`, стоящая перед глаголом и произносимая слитно с ним.

:numbered:
== Предлоги

include::articles/prepositions.adoc[]

:numbered:
== Обороты речи

Оборот `there is (there are)` соответствует русскому *имеется, есть, бывает, находится*, стоит на первом месте. Это выражение большей частью служит для указания наличия чего-либо в определенном месте. Предложение с оборотом `there is (are)` лучше всего переводить, начиная с обстоятельства места (*где?*)

====
There is a lamp on his table +
There are two books on his table +
There are many new houses there
====



Глагол to have (спряжение в настоящем времени):
	I 			have
	he/she/it 	has
	we 			have
	you 		have
	they 		have

***
Числительные порядковые

	Первые три порядковых числительных надо запомнить
		the first
		the second
		the third
	Признаком остальных порядковых числительных является суффикс -th
		the fourth
		the fifth
		the sixth
		...


***

Инфинитивом, или неопределенным наклонением глагола, называется та его форма, которая отвечает на вопрос: что делать? что сделать? Признаком инфинитива в английском языке является частица to, стоящая перед глаголом.


***

Степени сравнения прилагательных и наречий
В современном английском языке есть два способа образования степеней сравнения прилагательных:

	Первый способ - с помощью суффиксов. Этим способом образуются степени сравнения односложных прилагательных, а также тех двусложных, которые оканчиваются на y. В сравнительной степени к ним прибавляется суффикс -er, а в превосходной -est
		warm (теплый), warmer (теплее), warmest (теплейший, самый теплый)
		wide (широкий), wider (шире), widest (широчайший)
		ease (легкий), easier (легче), easiest (легчайший)

	Второй способ - путем прибавления слов more (более) и most (более всего, самый). Так образуются степени сравенния большинства двусложных и всех многосложных прилагательных.
		definite (определенный), more definite (определеннее), most definite (самый определенный)

	Кроме того, степени сравнения некоторых прилагательных образуются от других корней. Таких прилагательных не много:
		good (хороший), better (лучше), (the) best (лучший)
		bad (плохой), worse (хуже), (the) worst (худший)
		much (много), more (больше), (the) most (наибольший)

Степени сравнения наречий образуются аналогично степениям сравнения прилагательных:
	near (близко), nearer (ближе), nearest (ближе всего)
	solidly (крепко), more solidly (крепче), most solidly (крепче всего)

	И от других корней (нужно запомнить):
		well (хорошо), better (лучше), best (лучше всего)
		badly (плохо), worse (хуже), worst (хуже всего)
		much (много), more (больше), most (больше всего)
		little (мало), less (меньше), least (меньше всего)

***

Причастие I

	Английский язык, как и русский, имеет причастия (participles). Рассмотрим так называемое причастие I, которое называют также причастием настоящего времени (the Present Participle). Оно примерно соответствует русскому действительному причастию. Его признаком является суффикс -ing.
		open - opening (открывающий)
		live - living (живущий)
		study - studying (изучающий)
		let - letting (позволяющий)

	Функции причастия
		1) определение, стоящее перед определенным словом
			a flying bird (летящая птица)
			a dancing child (танцующий человек)
		2) с него может начинаться определенный причастный оборот, который обычно стоит после определяемого слова
			the boys studying geography (мальчики, изучающие географию)
		3) Причастие I может выражать обстоятельство и входить в обстоятельственный причастный оборот. В таких случаях он переводится деепричастием
			I write you this letter, knowing that you are very busy (Я пишу вам это письмо, зная, что вы очень заняты)
			Don't stand here, doing nothing (Не стойте здесь, ничего не делая)
			Hearing all this, I must answer (Услышав все это, я должен ответить)

***

Неопределенные местоимения some, any
	Местоимения some и any называются неопределенными, потому что выражают неопределенное количество
	Some значит "некоторые", "несколько" и употребляется в утвердительных предложениях:
		My friend has some good books (У моего друга есть несколько хороших книг)
		Some of these books are easy to read (Некоторые из этих книг легкие)
	Перед числительными some означает "приблизительно", "около":
		Some twenty men and women are present (Присутствует примерно двадцать человек)
	Any встречается преимущественно в вопросительных и отрицательных предложениях и имеет там то же значение, что и some в утвердительных. На русский язык any обычно вообще не переводится:
		Have you any pencils? (Есть ли у вас карандаши?)
		Are there any new houses here? (Есть ли здесь новые дома?)
		No, there aren't any (Нет, их нет)
	В утвердительных предложениях any значит "любой":
		Any man can tell you this (Любой человек может вам это сказать)
		Come at any time (Приходи в любое время)

***
The Past Indefinite Tense

	Прошедшее время стандартных глаголов образуется по стандарту: путем прибавления суффикса -ed
		to answer - I answered (я ответил)
		to act - he acted (он действовал)
		to ask - we asked (мы спросили)
	Глагол в прошедшем времени не изменяется по лицам

	Нестандартные глаголы (или неправильные) так называются потому что их формы образуются не по общему правилу, или стандарту.

	Вопросительная и отрицательная форма глаголов в Past Indefinite образуется аналогично тому, как образуются формы у глаголов в Present Indefinite. В утвердительной форме в Past Indefinite стоит смысловой глагол, в вопросительной форме в Past Indefinite стоит вспомогательный глагол, а смысловой глагол стоит в словарной форме. Отрицательная форма глаголов в Past Indefinite образуется при помощи слов did not, которые ставятся между подлежащим и смысловым глаголом, стоящим в словарной форме.

***

The Future Indefinite Tense

Это время выражает действие, которое должно совершиться в будущем. Оно образуется с помощью вспомогательных глаголов shall для первого лица и will для второго и третьего.

	we shall read
	you will read

Глаголы to be и to have образуют Future Indefinite таким же образом

	He will be a teacher
	I shall have a new dress

Модальные глаголы can, may, must в будущем времени не употребляются.
Вопросительная форма глаголов в будущем времени образуется путем перестановки - вспомогательный глагол ставится перед подлежащим

	Will you work?
	Will they come?

Отрицательная форма глаголов в Future Indefinite образуется с помощью not, которое ставится между вспомогательным и смысловым глаголами.

	I shall not see
	He will not do this

В разговорной речи shall и will сливаются с местоимением, а в отрицательной форме с not

	I shall - I'll
	he will - he'll
	shall not - shan't
	will not - won't


***
Существует три основные формы глагола
- Infinitive
- Past Indefinite
- Participle II
	Образование второй и третьей формы от стандартных глаголов не предстваляет трудности: обе эти формы образуются с помощью суффикса -ed.

***

Причастие II (Participle II)
Оно часто имеет в английском языке такое же значение, что и страдательное причастие в русском языке. Например, called (называемый), discussed (обсуждаемый), filled (наполненный). Оно часто выражает результат действия, которому подвергся предмет.

***
Предлоги by, with

Причастие II часто выражает результат действия, которому подверся предмет, что дает нам возможность считать его страдательным или пассивным причастием. Чтобы сказать, кто произвел это действие, употребляется существительное с предлогом by

	the letter written by a friend - письмо, написанное другом
	the apple eaten by a child - яблоко, съеденное ребенком

Примерно такое же отношение выражает предлог with с, употреблеющийся с названиями неодушевленных предметов (орудий труда и др.)

	a letter written with a fountain pen - письмо, написанное авторучкой
	a vessel filled with water - сосуд, наполненный водой

Сравнение причастий I и II

Первое часто имеет активное значение, а второе - пассивное:
	taking (берущий) 		taken (взятый)
	building (строящий) 	build (построенный)
	studying (изучающий) 	studied (изученный)
	using (использующий) 	used (использованный)

***
Герундий

Герундий - неличная форма глагола (неличными формами глагола в английском языке называются инфинитив, причастие и герундий, так как они не изменяются по лицам).
Герундий - это форма глагола, оканчивающаяся на -ing и имеющая свойства как глагола, так и существительного.
	teaching - преподавание
	planning - планирование

***
The Passive Voice (страдательный залог)

	Этот залог дает возможность образовывать предложения, в которых объект действия является подлежащим
		Бухгалтер составил смету (действительный залог)
		Смета была составлена бухгалтером (страдательный залог)

	Simple Passive состоит из вспомогательного глагола to be в соответствующем (настоящем, прошедшем или будущем) времени и причастия II смыслового глагола. Вопросительная форма в страдательном залоге образуется по уже знакомому принципу: первый (вспомогательный) глагол ставится перед подлежащим. Отрицательная форма образуется с помощью отрицания, которое ставится после первого глагола.
		Is anything changed?
		Will it be done?
		We are not invited.
		They were not seen.

	Нифинитив тоже имеет страдательный залог, образуемый с помощью глагола to be и причастия II смыслового глагола.
		Действительный 		Страдательный
		to do (делать)		to be done (быть сделанным)
		to write (писать)	to be written (быть написанным)

***

Времена группы Continuous Tenses
	Времена этой группы обозначают действия, которые протекают (протекали, будут протекать) в точно указанное настоящее, прошедшее или будущее время. Дополнительными характеристиками таких действий явлются их незаконченность, динамичтость и наглядность.

Active Voice
	to be ~~~~~-ing
Passive Voice
	to be being ~~~~~~-ed (3-форма)
	// в реальной жизни в пассивном залоге будущем времени не используется! т.е. считай что в Passive continuous future не существует

Отрицательная форма образуется с помощью отрицания not, которое ставится после первого (вспомогательного) глагола.
	He is not speaking
	We were not running

Времена Continuous отличаются от времен Indefinite своей большей конкретностью, наглядностью. Это видно из сравнения инфинитивов. Простой инфинитив, например, to work, означает работать. Соответствующий инфинитив в форме Continuous to be working буквально значит быть работающим, т.е. обозначает процесс продолжающийся, незаконченный.


********Сложнопридаточные предложения********

Главные типы
	Определительное: вводится словами who, whom, which, that, where
		I know the man who wrote this article
		It is an article which everybody read
		You can easily find the newspaper where his article was printed
		The house where I live is a new building
	Дополнительное: вводится обычно союзом than
		He says that his father is ill
		We see that you are busy
	Обстоятельное (времени, места, причины, условия и т.п.)
		We shall complete our studies before Comrade N. comes
		When they ask us we always answer
		She goes to the club, because she is invited
		If you want, I can read my translation to you

Бессоюзное подчинение придаточных предложений

	Дополнительные придаточные предложения
	Союз that часто опускают:
		I see that you are busy -> I see you are busy
		I know that you are right -> I know you are right
		I do not think your work was so difficult

	Определительные придаточные предложения
	В русских определительных предложениях слово "который" опустить нельзя. В английском языке возможно прямое присоединение определительных предложений к главному без слов who, whom, which, that
		The letter which I sent you was very long -> The letter I sent you was very long.
		The work that I am doing now is very difficult -> The work I am doing now is very difficult.

**************************************
Место предлога

	Русские предлоги настолько тесно связаны с существительными, что всегда стоят перед ними. В английском языке глагол может "перетягивать" предлог в конце предложения. Так например, вместо About what are you thinking? можно сказать What are you thinking about?
		What did you do it for?
		The car he was speaking about is very good.

	При бессоюзном введении придаточного предложения предлог может стоять только после глагола
		The man to whom you were speaking is our teacher
		The man you were speaking to is our teacher

		I must buy the book about which you told me
		I must buy the book you told me about

**************************************

Расстановка запятых в английском языке более произвольна, чем в русском и в большей степени зависит от желания пишушего придать пердложению определенное звучание, запятой обозначается небольшая пауза.

********Времена группы Perfect********

Времена действительного залога образуются при помощи глагола to have и причастия II смыслового глагола. Времена же страдательного залога образуются при помощи глагола to have плюс been (to have been - Perfict Indefinitive от глагола to be) плюс причастие II смыслового глагола.
Вопросительная форма глагола во временах группы Perfect образуется по общему правилу: первый вспомогательный глагол выносится вперед.
	Active
		Have I worked?
		Had I worked?
		Shall we have written?
	Passive
		Has it been done?
		Had it been done?
		Will it have been done?
Отрицательная форма образуется с помощью отрицания, которое ставится после первого глагола
	I have not worked.
	It has not been done.

Будущее время этой группы встречается настолько редко, что не стоит даже думать об этом.

Present Perfect, настоящее совершенное время, выражает связь прошлого с настоящим. Эта связь может выражаться двояко: во-первых, наличием результата ранее совершенного действия, во-вторых, продолжением в настоящее время действия, начавшегося в прошлом.
	Пример:
		Present Perfect: I have made a map. //Я сделал карту.
		Past Indefinite: Yesterday I made a map. // Вчера я сделал карту.
		Первое предложение указывает на результат действия: я сделал карту - карта сделана, карта существует в мометн разговора. Вротое предложение просто повествует о факте, который произошел вчера, не сообщая собеседнику о том, что делается с картой в момент разговора.
В тех предложениях, где Present Perfect выражает результат действия, он переводится прошедшим временем.
Но нередко встречаются предложения, где Present Perfect указывает, что действие, начавшееся в прошлом, еще продолжается в настоящем. В таких предложениях глаголы в Present Perfect часто нужно переводить настоящим временем
	I have lived in Kursk all my life // Я всю жизнь живу в Курске

	He has been ill for three months // Он болен (уже) три месяца
	He was ill for three months // От три месяца болел
В первом случае мы видим Present Perfect выражающий связь прошедшего с настоящим: человек заболел и продолжает болеть.
Present Perfect - это форма настоящего времени, и поэтому она не употребляется со словами, обозначающими время, определенно относящееся к прошлому, например yesterday, last year и т.д.
С глаголами в Present Perfect часто употребляются наречия неопределенного времени always, never, not yet, ever. Большей же частью предложения с Present Perfect не содержат никаких указаний о времени.

***********************************
The Past Perfect Tense

Past Perfect выражает действие, закончившееся до другого действия или момента в прошлом же. Поэтому можно считать как бы предпрошедшим временем. Переводится оно прошедшим временем, иногда с прибавлением уже.
	I saw that my friends has gone. // Я увидел, что мои друзья ушли
	Be six o'clock I had leraned all the words // К шести часам я уже выучил все слова


********Безличные предложения********
	В русском языке мы встречаем предложения без подлежащего - безличные и неопределенно-личные предложения
		Очень жаль.
		Темнеет уже в долине.
		Так было, но так больше не будет.
	В английском языке а аналогичных по смыслу предложениях имеется подлежащее, обычно выраженное местоимениями it, they, one иногда you
		It is late (Поздно)
		It is difficult to say (Трудно сказать)
		They say he is ill (Говорят, он болен)
		One must not smoke here (Здесь нельзя курить)
		You can never tell (Трудно сказать. Никогда нельзя сказать)

********Future-in-the-Paste********

По-русски мы употребляем будущее время глагола, не задумываясь о том, в каком времени глагола, не задумываясь о том, в каком времени ведется повествование в целом, употребляется ли будущее время в главном или придаточном предложении, и даже о том, совпадает ли это грамматическое время с реальным.
	Он будет лечиться в Крыму.
	В 1941 году мы были уверены, что победа будет за нами.
В обоих прежложениях мы видим будет, хотя в первом случае речь идет о реальном будущем, а во втором случае - об условном будущем, так как 1945 год является будущим лишь в отношении 1941 года, но прошлым по отношению к нашему времени.
В английском языке для этого относительного будущего есть особая форма, называемая Future-in-the-Past, т.е. "будущее в прошедшем". От простых будущих времен отличается лишь тем, что настоящее время вспомогательных глаголов shall, will заменяется соответственно их прошедшими временами should, would.
	The teacher told me that the next lesson would not be difficult.
	They said that the boiler would be soon made.
	I thought that I should get the book in their library.
	I did not know that your father would come.

********************************************************
Согласование времен

В русском языке времея глагола не зависит от того, в каком предложении употреблен данный глагол: в главном или в придаточном. Выбор времени определяется лишь смыслом.
	Я живу в Ростове.
	Я сказал, что живу в Ростове.
В обоих предложениях глагол стоит в настоящем времени. По-английски во втором примере прошедшее время в главном предложении не позволило бы употребить настоящее время в придаточном предложении. Поэтому в переводе на английский язык вышеприведенные примеры имеют такую форму:
	I live in Rostov.
	I said that I lived in Rostov.
Правило согласования времен состоит в следующем: при наличии прошедшего времени в главном предложении в дополнительном придаточном предложении настоящее и будущее время заменяются одним из прошедших времен, т.е. Past Indefinite, Past Continuous, Past Perfect, Future-in-the-Past. Но каким именно? Это зависит от смысла. Возьмем три случая. Действие, выраженное придаточным предложением, по отношению к действию, выраженному главным предложением, может быть:
	1. одновременным
		I said that it was possible. // Я думал что это возможно
		I thought that the child sleeping. // Я думал что ребенок спит
		В этом случае глагол в придаточном предложении ставится в Past Indefinite или Past Continuous и переводится на русский язык глаголом в настоящем времени.
	2. предшествующим
		We thought that you had heard. // Мы думали, что вы об этом (уже) слышали
		We knew it had been done. // Мы знали, что это уже сделано.
		В этом случае глагол стоит в Past Perfect и переводится на русский язык прошедшим временем. Напомню, что в этом отношении Past Perfect действительно является "прошедшим временем".
	3. будущим
		We knew that the sun would soon rise. // Мы знали, что солнце скоро взойдет.
		В таких случаях глагол стоит в Future-in-the-Past и переводится на русский будущим временем.

Правило согласования времен важно помнить при переводе. Особенно легко сделать ошибку в случае одновременности действий. Возьмем предложение: He said that he was a worker. (Он сказал, что он рабочий). Забыв о правиле согласования времен и переведя механически слово was глаголом в прошедшем времени, мы напишем "он сказал, что был рабочим" т.е. грубо исказим смысл. Наличие Past Indefinite в обоих предложениях (главном и придаточном) показывает, что действия одновременны. Если мы хотим сказать "... он был рабочим", мы должны употребить Past Perfect: He said that he had been a worker.

**************************************
Модальные глаголы и обороты

Модальные глаголы называют недостаточными, так как они имеют не все времена. Так, глаголы can и may имеют только два времени - настоящее и прошедшее (could, might), а глагол must - только настоящее. В недостающих временах они заменяются модальными оборотами.
	1. Возможность можно выразить словосочетанием to be able (иметь возможность, быть способным). Этот оборот можно относить к любому времени.
		I am able = I can
		I was able = I could
		I shall be able
	Невозможность часто выражается аналогичным оборотом: to be unable
		I was unable to see him
	2. Долженствование может быть выражено глаголами to have, to be, ought, should, need.
		- to have в качестве модального глагола синонимичен глаголу must, но может относится к любому времени
			I have to do it // Я должен это сделать
			I had to do it // Я должен был это сделать
			I shall have to do it // Я должен буду это сделать
		- to be в качестве модального употребляется для выражения долженствования в связи с заранее намеченным планом. Переводится словами должен, суждено, предстоит, нужно.
			I am to inform you... // Я должен вас известить
			He was to go to the south // Ему предстояло ехать на юг
			What is to be done? // Что делать?
			You are not to say anything // Вам не нужно ничего говорить
		- ougth употребляется только в данной форме вне зависимости от времени. Он выражает долженствование, являясь синонимом глагола must. Однако он менее категоричен, чем must, и часто применяется при совете.
			You ought to read more // Вам следует больше читать
			Your brother ought to smoke less // Вашему брату следовало бы меньше курить
		- should, выражает долженствование, но с оттенком сомнения в том, что должное действие будет совершено
			You should stop smoking // Вам следовало бы бросить курить
		- Модальный глагол need выражает долг или обязанность в вопросительных и отрицательных предложениях.
			Need you go so soon? // Вам обязательно нужно так скоро уходить?
			Need anybody know? // Разве нужно, чтобы кто-нибудь об этом знал?
			He needn't be told this. // Ему не обязательно об этом говорить
		Заметьте, что модальный глагол need образует вопросительную и отрицательную формы без вспомогательного глагола, а в третьем лице единственного числа не принимает никакого окончания: I need, he need и т.д. I need not, he need not и т.д. Употребляется этот модальный глагол только в Present Indefinite.
		Однако существует и смысловой глагол to need который имеет все формы, свойственные глаголам.
			He needs a dictionary.
			We do not need these cameras.
		Следует различать эти два глагола (модальный и смысловой), так как от них часто зависит смысл предложения
			He needn't be told // Ему не обязательно об этом говорить (пусть он лучше не знает)
			He does not need to be told // Ему об этом говорить не нужно (он и без нас это знает)
	3. Предположение, вероятность можно выразить глаголами can (could), may (might), must, should, а в отрицательных предложениях также глаголом need. При этом глаголы must, should выражают предположение, приближающееся к уверенности, а could и might - наиболее слабую вероятность или возможность.
		It could be so. // Возможно это так
		It may not be true // Возможно, это и неправда
		I might be wrong // Я могу ошибаться (не исключено, что я ошибаюсь)
		You must be cold // Вам наверное холодно
	Вариант перевода нужно выбирать по контексту.
	После глаголов can, may, must, should, need инфинитив теряет частицу to, но после глаголов to be, to have и ought она сохраняется.

***********************************
Многозначность as

	Do as I tell you // Делай, как я говорю
	As you see, I am busy // Как видите, я занят

	As I was busy I could not see him // Так как я был занят, я не мог с ним повидаться
	As the ship was coming in the port the sun rose // Когда корабль входил в порт, взошло солнце

	He is as tall as his brother // Он так же высок, как его брат

	Сочетание as ... as является основой ряда устойчивых оборотов, определяющих предел во времени или пространстве.
	I shall ask him as soon as he comes // Я спрошу его, как только он придет
	I shall walk with you as far as the station // Я дойду с вами до станции
	I need as much as a hundred roubles // Мне нужно целых сто рублей
	I need as many friends as you have // У меня столько же друзей, сколько у вас
	He was there as long as tree hours // Он был там целых 3 часа

	As long as имеет значение пока или раз
		As long as we have enought fuel the engine will work // Пока у нас достаточно горючего, машина будет работать
		As long as you are here, let's discuss the plan // Раз вы здесь, давайте обсудим план
	Сочетание as well as имеет два значения: так же хорошо, как и; а также
		He work as well as you do // Он работает так же хорошо, как и вы
		The book has been translated into English as well as into several other languages // Книга была переведена на английский язык, а также на несколько других языков
	Сочетание as if, as thought переводится "как будто"
		They looked as it they were busy // Они выглядели так, как будто были заняты
		The water was cold as thought it was not the Black Sea but the Whit Sea // Вода была такая холодная, как будто это было не Черное море, а Белое
	as for as to "что касается"
		As to the picture, I do not like it // Что касается этой картины, она мне не нравится
		As for me, I will help them // Что касается меня, то я им помогу

##Инфинитив и причастие как дополнение (винительный падеж с инфинитивом и причастием)
Рассмотрим два примера

***I asked him to come.***  *я попросил его придти.*
***I saw him do it.***  *я видел, как он делал это.*

В первом примере построение предложений - английского и русского - аналогично:
**1.** Подлежащее
**2.** Сказумое, выраженное глаголом
**3.** Дополнение, выраженное личным местоимением
**4.** Инфинитив другого глагола
Во втором английском предложении вы видите такое же построение. Но в русском переводе вы встречаете придаточное предложение. Дело в том, что по-русски такая инфинитивная конструкция возможна лишь после глаголов, выражающих воздействие на другое лицо, например, *просить*, *уговорить*, *убедить*, *заставить*. По-английски этот оборот употребляется не только после глаголов типа *to ask*, *to make*, *to let*, но и после глаголов чувствительного восприятия типа *to see*, *to hear*, *to feel* и др., а также после глагола *to want*. Инфинитив теряет частицу *to* после глаголов *let*, *see*, *hear* и других глаголов, выражающих чувствительное восприятие.

***I want you to translate the text*** *Я хочу, чтобы вы перевели текст.*
***We knew him to be busy.*** *Мы знали, что он занят*
***I heard him speak.*** *Я слышал, как он говорил*
***We did not see him come in.*** *Мы не видели, как он вошел*

В аналогичную конструкцию может входить не только инфинитив, но и причастие I.

***We saw them crossing the street.*** *Мы видели, как они переходили улицу.*
***We heard the boys talking in the next room*** *Мы слышали, как мальчики разговаривали в соседней комнате*

Существенного смыслового различия между инфинитивом и причастием в таких предложениях нет и, во всяком случае, на переводе оно не отражается.

***We saw John take the map = We saw John taking the map***

##Союзы *either ... or*, *neither ... nor*

Парный союз *either ... or* означает *или ... или*, *либо ... либо*; его антонимом является союз *neither ... nor* - *ни ... ни*

***She is either English or American*** *Она или англичанка, или американка*
***Either he or you will have to go*** *Либо ему, либо вам придется уйти*
***I saw neither your camera nor the pictures.*** *Я не видел, ни твоего фотоапарата, ни снимков*

Заметьте попутна, что без своих пар слова *either* и *neither* означают соответственно *любой* и *ни один*, *ни тот, ни другой*, *тоже не (нет)*

***Either of these coats is good enough for me.*** *Любое из этих пальто для меня достаточно хорошо.*
***I liked neither of these stories.*** *Ни один (ни тот, ни другой) из этих рассказов мне не понравился*
***I don't know him. Neither do you*** *Я его не знаю. Вы тоже*

##Возвратные и усилительные местоимения

Возвратные и усилительные местоимения образуются с помощью суффикса *-self*, имеющего значение *себя*, *сам*. Во множественном числе этот суффикс преобретает форму *-selves*.

*myself*
*yourself*
*himself*
*herself*
*itself*
*ourselves*
*themselves*

Усилительные местоимения соответствуют русскому *сам*:

***We ourselves saw them.*** *Мы сами их видели*
***You must do it yourself.*** *Ты сам должен это сделать.*

Возвратные местоимения соответствуют русским *-ся*, *себя*:

***He burned himself.*** *Он обжогся (обжог себя)ю*
***They saw themselves in the looking-glass.*** *Они увидели себя в зеркале*

##Perfect Continuous Tenses

Времена Perfect Continuous выражают длительные действия, начавшиеся до какого-то определенного момента и ещё продолжающигося в этот момент. Они соединяют особенности значения времени группы Continuous и группы Perfect. Present Perfect Continuous связывает прошедшее с настоящим, как и Present Perfect, выражая в то же время конкретность и непрерывность этой связи, характерную для времен группы Continuous. Образуются эти времена по одному принципу: глагол `to have` в соответствующем времени плюс `been` плюс причастие настоящего времени смыслового глагола.
В вопросительной форме первый из вспомогательных глаголов ставится перед подлежащим. Это время обычно переводится настоящим временем.

##Оборот "иминительный падеж с инфинитивом"

He is known to be a good scientist. *Известно, что он хороший ученый*
His methods are said to be very interesting *Говорят, что его методы очень интересны*

По-русски мы говорим например: *Предполагается, что собрание начнется в три часа. Слышали, как это сказал секретарь.* Мы не можем сказать *собрание ожидается начаться. секретарь услышан...* и т.д. Но по английски мы можем выразить эту мысл особым оборотом, представляющим собой сочетание глагола в личной форме с инфинитивом другого глагола.

The meeting is expected to open at three. *Предполагается, что собрание начнется в 3 часа*
The secretary was heard to say so. *Слышали, как секретарь это говорил*
He is considered to be a good speaker. *Его считают хорошим оратором.*

Такое построение характерно для выражения мнений, высказываний, наблюдений, т.е. для глаголов типа: *to say*, *to report*, *to see*, *to hear*, *to know*, *to believe*, *to expect*, *to consider*, *to think*...
Глаголы в этом обороте стоят, как правило, в страдательном залоге. Исключение составляют несколько глаголов, из которых вы знаете глагол *to seem*.

The story seems to be true. *Рассказ, кажется, правдив.*
The rhino was seen to lie among the grass. *Видели, что носорог лежал в траве*
The expedition is expected to return next month. *Ожидают, что экспедиция вернется в следующем месяце*

##Герундий

Герундий имеет свойства как глагола, так и существительного. Его глагольная природа выражается прежде всего в том, что он имеет формы времени и залога.

Залог			Active			Passive
Indefinite		inviting		being invited
Perfect			having invited	having been invited

Indefinite active
Reading is useful. *Чтение полезно*
Translating this article was not easy. *Переводить эту статью было нелегко*

Indefinite Passive
We do not like being laughed at. *Мы не любим, когда над нами смеются*
Thruogh being left out in the sun, the water got warm. *Вода стала теплой из-за того, что ее оставили на солнце*

Perfect Active
I told them about my having written a story *Я рассказал им о том, что написал рассказ*
They did not know about our having changed our opinion. *Они не знали, что мы изменили наше мнение*

Перфектный (Perfect) герундий как в действительном, так и в традательном залоге выражает действие, предшествующее действию, выраженному глаголом в личной форме. Так, в примере *I told them about my having written a story* перфектный герундий означает, что написание статьи произошло раньше, чем автор рассказал об этом.

They did not know about the plan having been completed. *Они не знали о том, что план уже завершен*
I was sure of the job having been finished. *Я был уверен, что работа уже закончена*

Из этих примеров видно, что простая форма герундий переводится обычно существительными или инфинитивом, а сложные формы герундия - придаточными предложениями.
Кроме наличия и залога, герундий имеет еще два глагольных свойства: он может иметь прямое дополнение и определяться наречием.

I have begun studying geology. *Я начал изучать (=изучение) геологию.*
He likes walking quickly. *Он любит быстро ходить*

Этим исчерпываются глагольные черты герундия. Герундий не изменяется по числам и лицам и поэтому относится к неличным формам глагола (Другими неличными формами глагола являются инфинитив и причастие).
Исторически герундий возник из отглагольного существительного. В современном английском языке встречается немало таких отглагольных существительных с окончанием `-ing`, например *building*
Сходство между герундием и существительным состоит в том, что герундий, как и существительное, может:

*. употребляться после предлога
*. определяться притяжательным местоимением или существительным в притяжательном падеже.

Различие состоит в том, что герундий не имеет множественного числа и артикля.

On reading his story I understand him better. *Прочитав (=после прочтения) его рассказ, я лучше его понимаю*
We know of his having done this. *Мы знаем, что он это сделал*
He went without looking back. *Он ушел, не оглядываясь.*

Функции герундия в предложении разнообразны. Герундий может быть подлежащим, частью сказуемого, дополнением, определением, обстоятельством. В силу этого разнообразия разнообразны и способы перевода герундия на русский язык.

Collecting this material took us a month (подлежащее). *Собирание этого материала заняло у нас месяц. (существительное)*
My job was collectiog the material (часть сказуемого). *Моей работой был сбор материала (существительное)*

##Инфинитив

в английском языке инфинитив имеет следующие шесть форм

					Active					Passive
Indefinite			to write				to be written
Continuous			to be writing			-
Perfect				to have written 		to have been written
Perfect Continuous	to have been writting	-

Сложные формы инфинитива имеют смысловые оттенки. Из них самое важное это то, что инфинитив в форме Perfect и Perfect Continuous выражает действие, предшествующее другому действию.

I like to read. (Infinitive Indefinite) *Я люблю читать*
He seemed to be thinking. (Infinitive Continuous) *Он как будто задумался*
I was happy to have received your letter. (Infinitive Perfect) *Я был счастлив получить ваше письмо.*
He seemed to have been making these experiments for a long time. (Infinitive Perfect Continuous) *Он, казалось, делал такие эксперименты уже в течении долгого времени*

После глаголов can, may, must, need и глаголов восприятия (видеть, слышать и т.п.) инфинитивы во всех своих формах теряют частицу `to`.

Инфинитив - определение следует за определяемым словом. Аналогичной конструкции в русском языке нет, и переводить инфинитив - определение большей частью приходится определительным придаточным предложением

He is not a man to do anything by halves. *Он не такой человек, который делает (=чтобы делать) что-либо наполовину.*
This is a good place to work in. *Это хорошее место для работы.*
There are not many people to believe this. *Не много есть людей, которые поверят этому*
This is the problem to be considered. *Эта та проблема, которую нужно рассмотреть (=подлежащая рассмотрению).*

Инфинитив - обстоятельство цели переводится инфинитивом, придаточным предложением или сочетанием "чтобы + инфинитив".

The teacher gave me a book to read. *Учитель дал мне почитать книгу.*
He went home to rest. *Он пошел домой отдохнуть.*
We have been sent here to study English. *Нас прислали сюда изучать английский язык.*
They did this to save their friend's life *Они сделали это, чтобы спасти жизнь друга.*
She opened the door to look into the room. *Она открыла дверь, чтобы заглянуть в комнату.*

Именительный падеж с инфинитивом

She is known to have been a dancer *Известно, что она (когда-то) была танцовщицей*
The mistake is said to have been found *Говорят, что ошибка (уже) найдена*
He appears to be suffering *Он, видимо, страдает*

##Слова-заменители

Во избежание повторения одного и того же слова некоторые слова, особенно существительные, иногда заменяются другими, чаще всего местоимениями. Например, по-русски мы говорим: *Иванов не пришел, он болен*. Такие замены делаются и в английской языке.

***One***

Give me a dictionary, the best one. *Дайте мне словарь, лучший (словарь)*
This is a good translation, but that one is full of mistakes. *Это хороший перевод, а тот (перевод) полон ошибок*
In our house there are three large B rooms and two small *В нашем доме три большие комнаты и две маленькие*

***That (of)***

Слово `that` (тот), в множественном числе `those` (те), заменяет существительное, часто перед предлогом `of`

I saw my own mistake and that of the other engineer. *Я увидел свою собственную ошибку и ошибку другого инженера*
His translations are better than those of his friend. *Его переводы лучше, чем переводы его друга*

***Вспомогательные глаголы***

Вспомогательные глаголы заменяют смысловые. Глаголы в простых временах (т.е. в формах, состоящих из одного слова) заменяются глаголом `do`. При наличии сложных форм глагола смысловой глагол опускается, а вспомогательный остается.

I like to read and so do my children. *Я люблю читать, и мои дети тоже (любят)*
He works as well as he did last year. *Он работает так же хорошо, как работал в прошлом году.*
The animals were aleeping and so were the birds. *Животные спали и птицы тоже (спали)*

При переводе английского текста важно учитывать существование слов-заместителей.

##few and little

Слова few и little переводится мало. Различие между ними заключается в том, что few употребляется с названиями предметов, которые можно сосчитать, в то время как little - с названиями веществ или понятий. Например, few books, little water. Различие между few и little аналогично различию между much и many.
Слова few, little в сочетании с артиклем а приобретают значение немного, некоторое количество. Это новое значение очень важно учитывать в переводе

We have few good pictures. *У нас мало хороших картин*
We have a few good pictures. *У нас есть несколько хороших картин*

He has little money. *У него мало денег*
He has a little money. *У него было немного денег*

Можно увидеть, что `few`, `little` имеют отрицательный оттенок, тогда как `а few`, `a little` - положительный.

##Причастия (сложные формы)

Причастия - это леличная форма глагола, она не изменяется по лицам и числам.

1) Причастие I в форме Indefinite обоих залогов в предложении отвечает на вопросы *какой*? и *как*? Отвечая на вопрос *какой*?, оно соответствует русскому причастию, отвечая на вопрос *как?*, оно соответствует русскому деепричастию.

We saw the rising sun. *Мы увидели восходящее солнце*
We saw the sun slowly rising in the east. *Мы увидели солнце, медленно встающее на востоке.*
Rising slowly, the could was covering the sun. *Медленно поднимаясь, облако закрывало солнце.*
Being written in English, the letter was not easy to understand. *Письмо было нелегко понять, так как оно было написано по-английски.*
Heving finished our work, we went home. *Окончив работу (поскольуо работа была окончена), мы пошли домой.*

2) Причастие II имеет только одну форму, в предложении большей частью отвечает на вопрос *какой?* и часто переводится причастием страдательного залога.

a letter written in ink *письмо, написанное чернилами рабитое стекло*
broken glass *разбитое стекло*
all the details known to you *все известные вам детали*

Многие причастия II в ходе развития языка превращаются в прилагательные. Вы знаете несколько таких слов: curved (изогнутый), learned (ученый).

3) Причастие I в форме Perfect обоих залогов обычно отвечает в предложении на вопрос *как?*, *при каких обстоятельствах?* и в этом отношении соответствует русскому деепричастию. Причастие в форме Perfect показывает, что выраженное им действие предшествует действию, выраженному сказуемым.

Having said that, I had to continue. *Сказав это, я должен был продолжать*
Having been invited to the meeting, we came in time. *Будучи приглашенными на собрание, мы пришли вовремя.*

Иногда различие между неопределенным и перфектным причастием можно выразить в переводе, употребляя в первом случае деепричастие несовершенного вида, а во втором - деепричастие совершенного вида.

coming - приходя
solving - решая
spreading - распостраняя
working - работая
having come - придя
having solve - решив
having spread - распостранив
having worked - проработав

###Причастие - определение

The street leading to our house is very wide *Улица, ведущая к нашему дому, очень широка.*
He is a leading scientist in this field. *Он ведущий ученый в этой области*
He is a man liked everybody. *Он человек, нравящийся всем.*
The cars now being produced at our works are very good. *Автомашины, производимые теперь на нашем заводе, очень хороши.*

###Причастие - обстоятельство

Knowing these words, you will be able to translate the text. *Зная эти слова, вы сможете перевести текст.*
Walking in the park, he met his old friend. *Гуляя в парке, он встретил своего старого друга.*
Having read the article, I do not need it any longer *Прочитав эту статью, я больше в ней не нуждаюсь*

###Причастие - именная часть сказуемого

He seemed interested. *Он казался заинтересованным.*
The window remained closed. *Окно оказалось закрытым.*

###Самостоятельный причастный оборот

В английском языке есть причастный оборот, не имеющий полной аналогии в русском языке. Он называется "самостоятельным" (а также "независимым" или "абсолютным") причастным оборотом. Такое название связано с тем, что в этом причастном обороте есть самостоятельное подлежащее.

A dark cloud having appeared in the sky, we decided to stay at home *На небе появилось темное облако, и мы решили остатся дома*
He read several books in English, the latest being a biography of Shakespeare. *Он прочитал несколько книг по-английски, причем последней книгой была биография Шекспира.*
The window haveing been closed, there was very little air in the room. *В комнате было очень мало воздуха, так как окно было закрыто*

##Форма на -ing

Подведем итог тому, что мы знаем о словах, оканчивающихся на -ing и часто объединяемых названием -ing-form.
Слово с суфиксом -ing может быть
*отглагольным существительным
*причастием
*герундием

Отглагольные существительные не представляют трудности, так как их легко можно узнать по артиклю или окончанию множественного числа. Например: a building, five buildings, the begining of the story.
Но отличить герундий от причастия I сразу не всегда легко, тем более что они совпадают не только в своих простых формах, но и сложных.

Признаки герундия:

1. Перед герундием может стоять предлог существительное в притяжательном падеже, притяжательное местоимение.

on coming
Jonhn's coming
their coming

2. Если герундий выполняет функцию обстоятельства, перед ним стоит предлог. Переводится герундий в таких случаях существительным с предлогом или деепричастием.

Eat something before starting.
On learning the news we left.

3. Перед названием предмета герундий обычно указывает на назначение этого предмета, отвечая на вопрос для чего? Переводится словосочетанием.

a dancing lesson
a sleeping bag
laughing gas

Признаки причастия

1. Причастие входит в состав времен группы

they are coming
it is being

2. Причастие в функции обстоятельства употребляется без предлога. Переводится деепричастием.

Standing at his side I saw everything.

3. Перед названием предмета - причастие обычно является его определением, отвечает на вопрос *какой?* и переводится причастием или прилагательным

a dancing child
a sleeping bird
a laughing girl

Важно понять, что в сочетании герундий + существительное речь идет не о свойстве, а о назначении предмета и что поэтому a sleeping bag - это не спящий мешок, а мешок, предназначенный для того, чтобы в нем спать, т.е. спальный мешок.
В сочетании герундий + существительное первый элемент имеет более сильное ударение, а в сочетании причастие + существительное оба слова являются равноударными. Дл правильного перевода при чтении следует из контекста, из общего смысла высказывания.

##Косвенный вопрос. Союзы if, whether

Косвенный вопрос вводится союзами if или whether, которым в русском языке соответствует частица *ли*

He asked me whether I was busy. *Он спросил меня, занят ли я.*
They asked if we could help them. *Они спросили, можем ли мы помочь им.*

С помощью этих же союзов строятся предложения следующих типов:

We wanted to know if they were at home. *Мы хотели узнать, дома ли они.*
I tried to find out whether he was still living. *Я пытался выяснить, жив ли он еще.*

Специальный косвенный вопрос вводится как и по-русски:

We asked him where he was born. *Мы спросили его, где он родился.*
She asked me what my name was. *Она спросила (меня), как меня зовут.*

Заметьте следующие особенности таких предложений:

1) В косвенном вопросе глагол стоит в утвердительной форме;
2) Он представляет собой дополнительное придаточное предложение, и поэтому на него распространяется правило о согласовании времен.

## Будущее действие в условных и обстоятельных придаточных предложениях

В предложении, излагающем условие или обстоятельство времени, будущее действие выражается глаголом в Present Indefinite:

She will do it if you ask her. *Она это сделает, если вы ее попросите*
When they get the letter they will let you know. *Когда они получат письмо, они дадут вам знать.*
They will not sign the agreement unless we accept their plan. *Они не подпишут соглашения, если мы не примем их плана.*

Таким образом, *Present Indefinite* выражает будущее действие после союзов типа `if`, `when`, `before`, `till`, `until`, `as soon as`, `unless`. В таких случаях глагол в *Present Indefinite* переводится на русский язык глаголом в будущем времени.

## Оборот to be going to

Для выражения предполагаемого будущего действия или события употребляется оборот *to be going to*.

I am going to tell him everything. *Я ему все скажу (собираюсь все ему сказать).*
He is not going to be a teacher. *Он не будет учителем (не хочет, не думает стать учителем)*

Этот оборот употребляется также для выражения намерения или предполагамеого события в прошлом:

Their farm was going to grow corn. *Их хозяйство собиралось выращивать курукузу.*
The foreign visitors were going to see our horses. *Иностранные гости собирались посмотреть наших лошадей.*

## Would

*Would* представляет собой прошедшее время от глагола *will*. Само по себе это слово не поддается переводу, но играет важную роль в сочетаниях. Перечислим его основные значения:

1) Would - это вспомогательный глагол для образования времени "будущее в прошедшем".

He said would be useless. *Он сказал, что это будет бесполезно.*
We knew that the news would soon spread all over the world. *Мы знали, что это известие скоро распространится по всему свету.*

2) Would имеет значение, близкое к значению русского "бы", и придает предложению оттенок желательности, совета, предположения или условности.

She would like to buy a new dress. *Она хотела бы купить новое платье.*
One would think that he had never seen her. *Можно (можно было бы) подумать, что он никогда ее не видел.*
I wouldn't do it. *Я бы этого не сделал (не советую так поступать)*
Who would have thought that of him! *Кто бы мог это о нем подумать!*
They would rather die than give up. *Они предпочтут скорее умереть, чем сдаться*

3) Would с отрицанием not может выражать несогласие, а в сочетании с перфектным инфинитивом - нереальное, воображаемое событие. Would not часто сокращается в wouldn't.

I told them about it, but they would not believe me. *Я им об этом рассказал, но они не поверили мне.*
We asked them to go, but they wouldn't. *Мы просили их уйти, но они не ушли.*
I wouldn't have mentioned it if I had know you were tired. *Я бы об этом не упомянул, если бы знал, что вы устали.*

В последнем примере would + Infinitive Perfect выражает нереальное, воображаемое событие, так как по смыслу предложения ясно, что я об этом упомянул.

4) Would употребляется для выражения повторного, привычного действия в прошлом.

He would sit there all day long? looking at his garden. *Он, бывало, сидел здесь целыми днями, глядя на свой сад.*

5) Would часто употребляется в учтивых просьбах и предложениях:

Would you like a cup of coffee? *Не хотите ли чашку кофе?*
Would you show us the way to the bridge? *Не укажете ли вы нам дорогу к мосту?*

## Сослагательное наклонение

В английской языке только глагол *to be* имеет особую форму сослагательного наклонения. Она очень проста: *were* для всех лиц.

(if) I were *если бы я был*
(if) he (she, it) were *если бы он (она, оно) был (была, было)*
(if) we (you, they) were *если бы мы (вы, они) были*
If I were younger ... *если бы я был моложе ...*
If the design were better ... *если бы конструкция была лучше*

Остальные глаголы особой формы сослагательного наклонения не имеют. Для выражения желательности, необходимости, возможности или предположительности действия употребляются формы, совпадающие с *Past Indefinite* или *Past Perfect*, а также глаголы *should*, *would*, *may*, *might*, *could* в сочетании с инфинитивами.

## Should

Should является формой прошедшего времени от глагола *shall*. В отрицательной форме *should* часто сливается с *not*: *should not = shouldn't*.
Основные значения should:

1) Should является вспомогательным глаголом для образования времени "будущее в прошедшем"

I knew I should meet him. *Я знал, что встречу его.*
He said we should soon see our friends. *Он сказал, что мы скоро увидим своих друзей.*

2) Should значит должен, он отличается от *must* меньшей категоричностью. Should - это не приказание, а совет, указание на моральную обязанность.

You should stop smoking. *Вам следовало бы бросить курить.*
It should be done immediately. *Это нужно сделать немедленно.*

3) Should в сочетании с Infinitive Indefinite часто значит *должен был бы делать, но не делаю*, а в сочетании с Indefinite Perfect - *должен был бы сделать, но не сделал.*

I should study tonight. *Мне следовало бы сегодня вечером заниматься (но я не занимаюсь).*
You should not smoke so much. *Вам не следовало бы так много курить (а вы курите).*
You shouldn't have said that. *Вам не следовало этого говорить (а вы сказали).*

4) Should выражает вероятность или возможность.

I think you should be able to translate the article. *Я думаю, что вы (вероятно) сможете перевести эту статью.*
That should be he. *Это, должно быть, он.*

5) Should часто употребляется в таких оборотах:

I should like *я хотел бы*
I should say *я сказал бы*
I should think *я бы полагал*

Should в этих сочетаниях придает высказыванию более скромный, учтивый, менее категоричный тон.


## Условные предложения

Английские условные предложения имеют ряд особенностей, которые необходимо учитывать для их правильного перевода. Рассмотрим основные типы таких предложений.
Высказывание условного содержания обычно состоит из придаточного предложения, выражающего условие, и главного предложения, выражающего вытекающее из условия заключение. Условное придаточное предложение обычно начинается союзами. if, provided, unless.
Такие предложения можно разбить на четыре основные группы, выражающие:

1. реальное условие
2. предположение
3. ререальное, противоречащее действительности условие в настоящем
4. нереализованное, несбывшееся условие в прошлом.

###Реальное условие

Такое условие выражает реальную зависимость одного действия от другого в настоящем или будущем времени.

If you know the subject, you need not be afraid. *Если вы знаете предмет, вам нечего бояться.*
If he is working, he cannot go with us. *Если он работает, он не может пойти с нами.*
If he said that, he was wron. *Если он так сказал, то он был неправ.*
If he was working, why did you disturb him? *Если он работал, почему вы его побеспокоили?*
I'll pay you, provided I get my wages tomorrow. *Я вам заплачу при условии, что (если) я завтра получу заработную плату.*
If he asks us, we'll tell him the truth. *Если он нас спросит, мы ему скажем правду.*
I shan't tell him anything, unless he asks me. *Я ничего ему не скажу, если он меня не спросит.*

###Предположение

Предположения, содержащие предположительное условие, говорят о будущем и состоит из: а) условия, выраженного Past Indefinite (здесь и дальше мы говорим о Past Indefinite и Past Perfect, хотя было бы точнее говорить о формах сослагательного наклонения, омонимичных этим временам. Мы позволяем себе это делать для краткости. Практического значения для нас это отступление от терминалогии не имеет) и б) вывода, выраженного should, would, could, might с Infinitive без частицы *to*. Выбор модального глагола определяет степень вероятности предположения.

If you studied more, you could learn English quickly. *Если бы вы больше занимались, вы могли бы быстро выучить английский язык.*
He would not agree, even if you asked him. *Он не согласится, даже если бы вы его об этом попросили.*

В условных предложениях такого типа глагол *to be* употребляется в форме сослагательного наклонения.

If he were taken ill, I should be sorry. *Если бы он заболел, мне было бы жалко.*

Таким образом, маловероятное условие можно выразить несколькими способами.

If he came
If he should come
If he were to come		ask him to wait
Should he come
Were he to come

Степень вероятности предположения несколько меняется, но важно понять, что предложения такого типа выражают предположение, а не факт.
В переводе таких предложений обычно употребляется сослагательное наклонение (с частицей бы).

###Нереальное условие в настоящем

Иногда возникает необходимость высказать предположение о том, что было бы, если бы условия были не теми, какими они являются в действительности, т.е. сделать нереальное, не соответствующее фактам предположение.
Нереальное предположение может делаться как в отношении настоящего, так и в отношении прошлого. Предложение *Если бы я знал английский язык, я бы ему ответил* выражает явно нереальное условие, так как из него явствует незнание говорящим английского языка. Но неизвестно, относится ли условие к настоящему времени (говорящий не знает английского языка и вынужден молчать) или к прошлому (говорящий выражает сожаление, что вследствие незнания языка ему пришлось промолчать). В английском языке для нереального условия в настоящем и прошлом есть разные формы.
Разберем сначала нереальное предположение в отношении настоящего. Оно выражается а) в условии - Past Indefinite (с глаголом were во всех лицах); б) в заключении - would, should, could или might плюс Infinitive Indefinite (Условные предложения типа 2 и 3 совпадают по форме, но не по смыслу)

If he were at home, we could go and see him. *Если бы он был дома, мы могли бы его навестить (но его нет).*
If I knew my lesson, I should be happy. *Если бы я знал урок, я был бы счастлив (но я его не знаю).*
If I were you, I would not speak about it. *На вашем месте я бы об этом не говорил (но я не вы).*

###Нереализованное условие в прошлом

Нереализованное, не соответствующее действительности предположение в отношении прошлого выражается:

а) в условии - Past Perfect
б) в заключении - should, would, could или might плюс Infinitive Perfect

If you had given me more time, I should have made a better report. *Если бы дали мне больше времени, я бы сделал доклад лучше*
If they had mentioned this yesterday, everything would have been done. *Если бы они упомянули об этом вчера, все было бы уже сделано*

##Бессоюзные подчинение условных предложений

Условные предложения могут присоединяться к главному и без союза. Это возможно только при наличии вспомогательного глагола, который в таком случае ставится на первое место.

If I had know it before ... Если бы я знал об этом раньше
Had I known it before ...

If I were less tired ... Если бы я был менее усталым
Were I less tired ...

Основная трудность распознавания типов условных предложений состоит в следующем: в английском языке мы имеем разные формы для того, что по-русски мы выражаем одинаково. Возьмем русское предложение: *Если бы я выиграл много денег, я бы купил автомобиль*. Не зная обстановки, в которой сказаны эти слова, вы не сможете точно определить, выражает ли говорящий предположения о будущем или излагает несбывшееся условие в прошлом. Это предложение можно истолковать двояко: 1) *если я когда-либо выиграю много денег, я куплю автомобиль* (предположение о будущем); 2) *если бы я выиграл, я бы купил автомобиль* (но я не выиграл и поэтому не купил). По-английски же эти две мысли выражаются по-разному.
Мы разобрали основные типы условных предложений, но в литературе могут встречаться и сочетания этих типов.