:numbered:
= Построение сложных английский предложений

Основными союзами, использующимися для соединения двух (или более) простых предложений в одно сложносочиненное, являются следующие: *and, but, however, nevertheless, or, still*. Иногда союз не ставится вообще, простые предложения в составе сложносочиненного разделяются запятой или отчкой с запятой.

Можно строить предложения, описывающие ситуации, которые включают в себя несколько действий, при этом действия могут быть:

* Одинаковыми по степени важности в предложении, выполняющимися одним и тем же предметом в одно и то же время

====
* Он открыл дверь и увидел нас -> He opened the door and saw us
* Она остановилась, закрыла глаза и толкнула дверь -> She stopped, closed her eyes, and pushed the door
====

* Одинаковыми по степени важности в предложении, но выполняющимися разными предметами

====
* Я ее люблю, а она меня не любит -> I love her, and she doesn't love me
* Мы использовали новую жидкость, но это (она) не помогало -> We used a new liquid but it didn't help
====

* Разными по степени важности в предложении, т.е. одно какое-либо действие в предложении является главным, а другое (другие) - вроростепенным, зависящим от главного или подчиняющимся ему

В английском языке существует две возможности построения предложений с описанием двух или более действий, разных по степени важности:

1. С помощью главных и придаточных предложений (сложноподчиненных).

====
We saw a man who was smoking a big cigar
====

2. С помощью неличных форм глагола (инфинитив, герундий и причастие)

Неличные формы глагола не обладают признаками времени, лица, числа, наклонения. Они никогда не могут самостоятельно выступать в предложении в качестве сказуемого, обозначая лишь какое-либо второстепенное действие или входя в состав сказуемого в качестве одной из составных частей.

:numbered:
== Придаточные предложения

В английском языке, так же, как и в русском, придаточные предложения делятся на несколько типов: *придаточные подлежащие/сказуемые/дополнительные/определительные/обстоятельные*. Придаточные обстоятельственные, в свою очередь, подразделяются на: *придаточные места/времени/причины/условия/цели/сравнения/образа действия/следствия/придаточные уступки*.

Пусть не смущает такое большое колличество типов придаточных предложений. Для того, чтобы правильно пользоваться придаточными предложениями при переводе с одного языка на другой, достаточно знать лишь основные их типы, значения союзов, присоединяющих эти придаточные к главному предложению и не выходить за рамки установленных правил, которые рассмотрим ниже.

=== Основные союзы, использующиеся для присоединения придаточных предложений.

that:: *что/чтобы* в разговорной речи часто опускается, но легко угадывается по смыслу

====
I know *(that)* he is a good driver
====

because:: *потому что*

====
I like you *because* you are a good girl
====

as:: *как/так как*

====
*As* they were busy, we went without them
====

if:: *если*

====
I'll help you *if* you come
====

if/whether:: *ли*

====
* I don't know *if/whether* he smokes
* Nobody can tell you *whether/if* she spoke to him
====

союзы *if/whether* очень близки по значению и используются для присоединения придаточных предложений, напоминающих по форме общие вопросы. Единственным отличием, существующим между этими союзами, является то, что *whether* может использоваться перед инфинитивом, а *if* - не может

====
* I don't know *whether* to do it or not
* I don't know *whether/if* I want to do it or not
====

when:: *когда*

====
I was out *when* she came
====

since:: *поскольку/так как*

====
I can't buy this *house* I have no money
====

since:: *с тех пор, как* (подразумевает незаконченный промежуток времени, поэтому в главном предложении используются формулы *_Perfect_*

====
There have been no letters from him *since* he left
====

after:: *после того, как* (если подчеркивается предшествование одного действия другому, сказуемое придаточного ставится в *_Perfect Past_*; если одно действие просто следует за другим - *_Indefinite Past_*

====
She came *after* I had left/I left
====

before:: *перед тем, как* (если подчеркивается предшествование одного действия другому, сказуемое главного ставится в *_Perfect Past_*; если одно действие просто следует за другим - *_Indefinite Past_*

====
She had left/She left *before* I came
====

till/until:: *до тех пор, пока (не)* (в этом случае сказуемое придаточного предложения используется в утвердительной форме

====
Wait here *till/untill* I come back
====

while:: *пока/в то время как*

====
He left *while* I was smoking
====

unless:: *если не* (сказуемое придаточного предложения используется в утвердительной форме

====
He will leave *unless* you help him
====

though/although:: *хотя*

====
I'll help you *though/although* I am busy
====

as though/as if:: *как если бы/как будто*

====
* You look *as if* you haven't slept
* It smells *as though* someone has been smoking in here
====

than:: *чем*

====
I know her better *than* you (do)
====

so that:: *так что*

====
He didn't want to help us, *so that* we had to leave
====

so... that:: *так/настолько..., что*

====
He was *so* tired *that* we had to wait
====

as... as:: *так (же)/такой (же), как (и)*

====
He doesn't love you *as* much *as* you love him
====

not so... as:: *не так/такой..., как*

====
This book is *not so* interesting *as* I expected
====

that/so that/in order (that):: *чтобы/для того, чтобы*

====
He asked me for some money *in order (that)/so that* he could buy a new car
====

lest:: *чтобы не*

====
I was afraid *lest* he see me
====

the... the:: *чем... тем* (в этом случае используются прилагательные/наречия в сравнительной степени)

====
*The* more you smoke *the* less I like you
====

provided (that)/on condition (that):: *при условии, что*

====
She will come *provided/on condition (that)* you help her
====

supposing (that):: *допустим/предположим (что)*

====
*Supposing (that)* I give you some money, what will you do?
====

as:: *в то время, как/когда/по мере того, как*

====
It happened *as* I was cleaning the room
====

as soon as:: *как только*

====
I'll call you *as soon as* they come back
====

as/so long as:: *пока/при условии, что*

====
Don't smoke in the room *as/so long as* I am here
====

in case (that):: *в случае, если*

====
*In case (that)* he can't help you, call me
====

Часто для присоединения придаточных предложений к главному или к другому придаточному используются союзные слова (совпадают по форме с вопросительными словами). Они не просто соединяют предложения друг с другом, но и являются членами придаточного предложения, иногда даже подлежащим

====
I don't know *who* helped him
====

Русские придаточные предложения со словом *который* переводятся на английский с помощью слов *who* (для одушевленных) или *which* (для неодушевленных)

====
* The boy, *who* helps you, is my son
* The cigar, *which* I am smoking now, is very strong
====

иногда *which* может заменяться на *that*, а в разговорной речи часто опускается

====
* The cigar, *that* I am smoking now, is very strong
* The cigar, I am smoking now, is very strong
====

Если слово *who* надо поставить в предложении с предлогом, то чаще используется форма *whom*. Предлоги ставятся перед *whom* или *which*, но если сами слова в предложении отсутствуют, то предлог стоит после сказуемого

====
* The young girl, *about whom* I want to tell you, doesn't live here
* The young girl, I want to tell you *about*, doesn't live here
====

=== What или That

Иногда при переводе с русского языка на английский придаточных предложений с союзом *что* возникают затруднения в выборе английского эквивалента союза. Запомните: если, отделив придаточное предложение от главного, получаем по форме обычный вопрос, начинающийся словом *что* под ударением, то в английском предложении ставится *what*; если вопросительной формы не получается - *that*

====
* Я знаю, *что* ты хочешь -> I know *what* you want
* Я знаю, *что* ты не придешь -> I know *(that)* you won't come
====

союз *that* в разговорной речи часто опускается, слово *what* никогда не опускается

Если в качестве придаточного предложения используется форма общего вопроса, то в русском языке ставится *ли*, которому в английском соответствует *if/whether*

====
I don't know, *if/whether* they will be able to buy a new house here
====

Если все сложноподчиненное предложение построено в форме вопроса, состоящего из двух вопросительных предложений, то главное строится по схеме вопроса, а придаточное - как обычное повествовательное

====
Do you know why he is sleeping now?
====

Все вопросительные слова, кроме *whom/whose* и *why* образуют формы посредством прибавления в конце слова *-ever* (бы ни), которые тоже используются для присоединения придаточных предложений

====
* whatever -> что бы ни
* whoever -> кто бы ни
* whenever -> когда бы ни
* however -> как бы ни
* whichever -> какой бы ни
* wherever -> где бы ни
====

====
* *Whatever* you do, I'll help you
* *Wherever* he went, I fallowed him
====

В этом случае в придаточнх предложениях не используется *_Future_*

====
*Wherever* you go, I'll follow you
====

*_Future_* не используется также в придаточных времени, (отвечающих на вопрос *когда?/до каких пор?*) и в придаточных условия (*при каких условиях?/в каком случае?*). Здесь вместо будущего времени сказуемое придаточного предложения ставится в настоящем времени *_(Present)_*. Это относится ко всем формулам

====
* As soon as you call me, I'll send you the money
* We will bring new books if your friends invite us
* When my husband buys a new car, we'll be able to visit you more often
====

описанный только что случай относится лишь к указанным в нем предложениям; придаточные предложения, в которых используются союзы *if/when*, но которые не отвечают на перечисленные выше вопросы, строятся по общим правилам, т.е. в них ставится *_Future_*

====
* I don't know when he will come
* I don't know if he will come
====

Одним из самых важных моментов в изучении придаточных предложений является такое понятие как *согласование времен*, относящееся только к придаточным дополнительным (отвечают на вопрос *что?*), которые присоединяются к главному или к другим придаточным союзами *that/it/whether* или союзными словами, совпадающими по форме с вопросительными (с предлогами или без предлогов) словами.

В английском языке существует правило (в русском языке такого правила нет), что, если сказуемое главного предложения стоит в прошедшем времени *_(Past)_*, то и сказуемое придаточного предложения тоже должно стоять в форме *_Past_*. Если же сказуемое главного предложения стоит в настоящем *_(Present)_* или будущем *_(Future)_* времени, то сказуемое придаточного может ставиться в любое нужное по ситуации время

====
* I know (that) he often comes here
* I know (that) he came yesterday
* I know (that) he will come tomorrow
====

====
* I knew (that) he came here -> Я знал, что он приходит сюда (оба действия происходили одновременно в прошлом)
* I knew (that) he comes here -> Я знал, что он приходит сюда (приходил раньше и продолжает приходить сейчас)
* I knew (that) he came here -> Я знал, что он приходил сюда (оба действия происходили одновременно в прошлом)
* I knew (that) he had come here -> Я знал, что он приходил сюда (приходил раньше, т.е. когда знал, то больше уже не приходил)
====

Как же быть с предложениями типа: *Я знал, что он придет сюда* (в главном предложении *_Past_*, значит в придаточном (по правилу) тоже должно быть *_Past_*, но в русском варианте будущее время *_(Future)_*)

Для таких случаев в английском языке сущетсвует форма сказуемого придаточного предложения, называемая *_Future-In-The-Past_* (будущее в прошедшем). Она образуется переходом вспомогательного глагола *shall* в форму *should*, а *will* - в *would*, после чего ставится нужная форма *_Infinitive_* (вся формула) без частицы *to* _(should (would) help/should (would) be sleeping/should (would) have helped и т.д.)_

====
* I knew (that) he *would* come here
* We were informed that they *would* speak Russian
====

Если придаточное дополнительное присоединяется к главному предложению с помощью союзного слова с предлогом, то предлог ставится после сказуемого (или перед обстоятельством времени), хотя относится к союзному слову (аналогично специальному вопросу):

====
* Who(m) did she some with?
* He didn't notice whom she came with
* Where does she come from?
* Nobody knows where she is from
====

Если к одному главному предложению, сказуемое которого стоит в *_Past_*, есть два придаточных в *_Future_* с последовательным подчинением, то сказуемое первого придаточного ставится в форме *_Future-in-the-Past_*, а сказуемое второго - в *_Past Indefinite_*

====
* He felt that they wouldn't be sleeping when he came back
* He hoped that they wouldn't tell her why he went there
====

Косвенная речь, т.е. когда передаются не подлинные чьи-то слова (прямая речь), а только их соделжание, тоже представляет собой не что иное, как придаточное дополнительное, и строится по тем же правилам. При этом русскому *сказать* могут соответствовать в переводе два английских глагола: *to say* (когда не указывается кому; или же, когда указывается кому - обязательно с предлогом *to*) или *to tell* (только когда указывается кому и без предлога)

====
* He said (that) he wouldn't be able to come tomorrow
* He told us (= He said to us) (that) he wouldn't go there
====

Согласование времен не используется при обозначении общеизвестных фактов, а также при обозначении обычных/регулярных действий, которые продолжают происходить в настоящий момент

====
* We knew (that) smoking is bad for health
* He didn't know what time the train usually starts
====

:numbered:
== Сослагательное наклонение

Сослагательное наклонение показывает, что говорящий рассматривает действие не как реальный факт, а как нечто желаемое/возможное/предполагаемое и т.п.

В русском языке существует всего одна форма, обозначающая сослагательное наклонение: *глагол в прошедшем времени + бы*: хотел бы/узнал бы/ждал бы. В английском языке для обозначения сослагательного наклонения существует несколько форм.

NOTE: формы сослагательного наклонения в главном и придаточном предложениях обязательно должны отличаться друг от друга

Формы сослагательного наклонения делятся на два вида:

1. используется при обозначении настоящего и будущего времени
2. используется при обозначении прошедшего времени, т.е. оказавшегося невыполенным действия

С определения вида нужной формы и следует начинать анализ любой ситуации при переводе сослагательного наклонения с русского языка на английский.

=== формы сослагательного наклонения первого вида

в английском языке формы сослагательного наклонения 1-го вида служат для выражения совета/желания/предложения и т.п., а также для описания нереальных ситуаций, относящихся к настоящему или будущему времени. Используются как в простых, так и в сложноподчиненных предложениях.

В простых предложениях могут использоваться только формы, состоящие из двух глаголов:

====
* I should/(would like = I'd like) to see your house
* You could do it later
* He might be very helpful
* Would you go there with us?
* You should be more careful
====

Сложноподчиненные предложения (сказуемое главного и сказуемое придаточного обязательно должны различаться). Придаточные предложения отвечают на вопрос *что?*. Сказуемое главного предложения выражено глаголом *to be* в *_Past/Present/Future_*, т.е. не является формой сослагательного наклонения. Сказуемое придаточного совпадает по форме с *_Infinitive_* без частицы *to*. Придаточные имеют модальное значение, поэтому можно использовать также *should* для всех лиц. Для присоединения придаточного предложения к главному используется союз *that*, который можно опускать. В русском языке в подобных случаях не обязательно сослагательное наклонение. Такие предложения начинаются выражениями:

* *it is/was/will be important* -> важно/было важно/будет важно
* *it is necessary* -> необходимо
* *it is possible* -> возможно
* *it is probable* -> возможно
* *it is desirable* -> желательно
* *it is likely* -> вероятно/скорей всего

====
* It is important (that) you be/should be here tomorrow at 5
* It is likely that he should meet you at the airport
* It was necessary that she help us
* It will be desirable that she should come alone
====

Придаточные сказуемые отвечают на вопрос *состоит/заключается в чем?*. Сказуемое главного предложения выражено глаголом *to be* в *Past/Present/Future*, т.е. не является формой сослагательного наклонения. Сказуемое придаточного совпадает по форме с *_Infinitive_* без частицы *to*. Придаточные имеют модальное значение, поэтому можно использовать также *should* для всех лиц. Для соединения предложений используется союз *that*, который нельзя опускать

====
* Our proposal was that all workers be given/should be given milk
* Our advice is that you shouldn't smoke
* Their suggestion will be that we should use a stronger liquid
====

Придаточные дополнительные. Сказуемое главного предложения выражено глаголами:

* *to recommend* -> рекомендовать
* *to propose* -> предлагать
* *to suggest* -> предлагать
* *to insist* -> настраивать
* *to demand* -> требовать
* *to order* -> приказать
* *to wish* -> желать и др.

Сказуемое главного предложения не является формой сослагательного наклонения. Сказуемое придаточного совпадает по форме с *_Infinitive_* без частицы *to* или *_Indefinite Past_*. После глагола *to wish* ставится форма, совпадающая с *_Indefinite Past_* или форма с *would*. Придаточные имеют модальное значение, поэтому можно использовать *should* для всех лиц. Для присоединения придаточного предложения к главному используется союз *that*, который обычно опускается после глагола *to wish*

====
* We insist that you call/called/should call him
* What do you suggest we do/did/should do?
* I wish (that) you could come back tomorrow
====

*Wish* стоит обычно с местоимением *I*, в разговорной речи последнее можно опускать, потому что оно легко угадывается по смыслу

====
* I wish they gave/would give me more money
* I wish it would stop/stopped snowing
====

Придаточные обстоятельственные:

1. *цели* - отвечают на вопрос *с какой целью?*; присоединяются к главному союзами *so that/in order that -> для того, чтобы*, после которых используются формы *might/should/would ~~~~*; или союзом *lest -> чтобы не*, после которого используется только форма *_Infinitive_* без *to* или *should/might ~~~~; lest* заключает в себе отрицание, поэтому форма сказуемого после этого слова не должна быть отрицательной

====
* Give me your money so that I should/would not be worried
* You have to be careful in order that you might do everything correctly
* You have to be careful lest you make/might/should make a mistake
====

2. *уступки* - отвечают на вопрос *несмотря на что?*; в качестве сказуемого придаточного предложения используются разные формы 1-го вида; присоединяются к главному союзами:

* *(even) though/although* -> (даже) хотя
* *even if* -> даже если бы
* *whenever* -> когда бы ни
* *whatever/whoever* -> что бы ни/кто бы ни и др.

====
* Even if he were/was here wouldn't help you
* Whatever you might do to me, I like you
* She won't come though she would like to (come) very much
====

3. *образа действия и сравнения* - отвечают на вопрос *как?/каким образом?*; сказуемое придаточного предложения совпадает по форме с *_Indefinite Past_*;

присоединяются к главному союзами *as if/as though -> как если бы/будто бы*

====
* She is cleaning the room as if/as though she were/was a cleaner
* He behaves as though he knew nothing about it
====

=== Формы сослагательного наклонения 2-го вида

В английском языке формы сослагательного наклонения 2-го вида служат для выражения сожаления/досады/возмущения/упрека по поводу того, что какое-либо действие могло бы произойти/оказалось невыполненным/произошло не вовремя. Используются как в простых, так и в сложноподчиненных предложениях.

* Простые предложения:

====
* Oh God! You might have been killed!
* He should have helped you
* They ought to have come earlier
====

* Сложноподчиненные предложения

1. Придаточные дополнительные.

В этом случае в качестве сказуемого главного предложения используется глагол *to wish*, а русский перевод начинается словом *жаль*

====
* I wish I had come earlier
* I wish you had not been there
* I wish I had invited you
====

2. Придаточные сравнения

====
* He looks as if he had got married
* Why are you looking at me as if you had not seen me for years?
====

=== Придаточные предложения условия

Используются в английском языке для описания ситуаций с различными признаками.

При построении таких предложений мы должны быть внимательны и тщательно проанализировать ситуацию в русском языке, прежде чем переводить ее на английский - от этого зависит правильный выбор формы сказуемого в придаточном условия.

Всего существует 3 варианта придаточных условных предложений:

1. Без сослагательного наклонения - для описания ситуаций, в которых действие представляется реально выполнимым при каком-либо условии. При этом сказуемое главного предложения стоит в *_Future_*, а сказуемое придаточного - в *_Present_*

====
* If he comes to take us, we'll be able to go to the cinema
* If he is sleeping, we will wait
====

Придаточное предложение может иметь обратный порядок слов

====
Should he be sleeping, we will wait
====

2. Используются формы сослагательного наклонения 1-го вида - для описания ситуаций, в которых выполнение действий представляется маловероятным, но при этом какая-то возможность его выполнения все-таки существует/остается. Вся ситуация воспринимается в настоящем времени

====
If he came to take us, we could go to the cinema
====

Сказуемое придаточного предложения стоит в форме, совпадающей с *_Indefinite Past_*, а сказуемое главного - в форме, состоящей из двух слов

====
* If he was/were here, he could do it
* We could buy this house if we had money
* He wouldn't lend me any money if I asked him
* Were he here, he could do it
====

3. Используются формы сослагательного наклонения 2-го вида - для описания ситуаций, в которых действие уже никак невыполнимо (момент для его выполнения упущен). Вся ситуация воспринимается в прошедшем времени

====
* If he had come to take us, we could have gone to the cinema
====

Сказуемое придаточного предложения совпадает по форме с *Perfect Past*, а сказуемое главного - в любой другой форме 2-го вида

NOTE: описание ситуаций в пунктак 2 и 3 выглядит по-русски совершенно одинаково (потому что в русском языке для сослагательного наклонения существует всего одна форма), но в действительности эти ситуации совершенно разные

====
* If he had been here, he could have done it
* We could have bought this house if we had money
====

Придаточное предложение может иметь обратный порядок слов

====
Had he been here, he could have done it
====

:numbered:
== Инфинитив

Инфинитивом, или неопределенным наклонением глагола, называется та его форма, которая отвечает на вопрос: *что делать? что сделать?* Признаком инфинитива в английском языке является частица `to`, стоящая перед глаголом и произносимая слитно с ним.

Во многих случаях свойства и функции инфинитива в предложении в обоих языках совпадают и, следовательно, не вызывают никаких проблем с переводом. Поэтому мы не будем подробно останавливаться на таких случаях.

====
* I went to help you
* He came here to see our new house
====

В некоторых случаях частица `to` перед инфинитивом не ставится:

* после модальных глаголов, кроме *ought*
* после некоторых глаголов в объектном инфинитивном обороте (см. ниже)
* после глагола *let*
* после глагола *to make* в значении *заставлять _(Active)_*: _He *made* me help him. What *makes* you say that?_

NOTE: после глагола *to make* в значении *заставлять _(Passive)_* инфинитив ставится с частицей `to`: _I was *made* to help him. She was *made* to repeat the story_

* после выражений *would/had rather* -> предпочел бы / *had better* -> лучше бы и некоторых других

====
* She *would rather* help them
* You *had better* help her
====

* Если в предложении два инфинитива соединаются союзами *and* или *or*, то перед вторым частицу `to` можно не ставить.

====
I want to come and (to) see your new house
====

* После глаголов *shall/will/should/would* используется только форма инфинитива без частицы `to`

NOTE: главным отличием английского инфинитива от русской неопределенной формы является то, что инфинитив распадается еще на несколько форм, в каждой из которых заключено понятие залога *_(Active/Passive)_* и характера действия *_(Indefinite/Continuous/Perfect/Perfect Continuous)_*, т.е. получаются все те же формулы, только без значения времени (формула *_Passive Continuous_* не используется самостоятельно в качестве инфинитива)

Формы *_Indefinite Infinitive (Active/Passive)_*, а также *_Active Continuous Infinitive_* обозначают действие, происходящее одновременно с действием, обозначенным сказуемым предложения:

====
* I am glad to help you -> Я рад помочь тебе
* I am glad to be helping you -> Я рад, что помогаю тебе
* I am glad to be helped -> Я рад, что мне помогают
====

Формы *_Perfect Infinitive (Active/Passive)_*, а также *_Active Continuous Infinitive_* обозначают действие, предшествовавшее действию, обозначенному сказуемым, при этом различаются оттенки:

1. обычное совершившееся действие:

====
* I am glad to have helped you -> Я рад, что помог тебе
* I am glad to have been helped -> Я рад, что мне помогли
* I am glad to have been helping you -> Я рад, что помогаю тебе (в течении какого-то времени до настоящего момента)
====

2. действие, которое оказалось невыполненным вопреки надежде (после *to hope*)/ожиданию (после *to expect*)/намерению (после *to intend*)/предположению (после *to mean*); все перечисленные глаголы выступают в качестве сказуемого и стоят в *_Indefinite Past_*

====
* I hoped to have been helped -> Я надеялся, что мне помогут (но не помогли)
* She expected to have been called -> Она надеялась, что ей позвонят (но не позвонили)
* They intended to have come earlier -> Они собирались/рассчитывали прийти раньше (но не смогли)
* I meant to have invited them -> Я предполагал пригласить их (но что-то помешало мне сделать это)
====

3. использование форм *_Perfect Infinitive_* после модальных глаголов.

=== Особые случаи использования инфинитива в английском языке

1. В функции обстоятельства цели или следствия, когда часто переводятся на русский язык придаточными предложениями

====
* (In order) *To be* there on time we must hurry -> Чтобы быть там вовремя, нам надо торопиться
* He was too tired *to help* us -> Он был слишком уставшим, чтобы помочь нам
====

2. В функции определения, когда инфинитив отвечает на вопрос *какой?*. В некоторых случаях, когда инфинитив следует сразу за существительным или местоимением, он может обозначать действие, которое должно быть или будет выполнено в отношении этого существительного/местоимения потому, что они обладают определенными качествами или признаками

====
* I brought you some water to drink -> Я принес тебе воду (какую?) которую ты можешь пить
* Have you got anything to declare? -> У вас есть что-нибудь (какое?), что нужно вносить в декларацию?
* This is a good house to be bought -> Это хороший дом, его можно покупать
====

NOTE: инфинитив, занимающий место сразу после существительного или местоимения, не всегда выполняет функцию определения, например

====
* I asked my friend to help me -> Я попросил своего друга помочь мне
* He is a good friend to be invited -> Он хороший парень, его можно пригласить
====

В рассмотренных нами ситуациях можно использовать как форму *_Active Indefinite Infinitive_* (если речь идет о назначении предмета)

====
I bought you some water to drink
====

так и форму *_Passive Indefinite Infinitive_* (если действие должно быть или будет выполнено в отношении предмета из-за наличия у него определенных качеств)

====
This is a good house to be bought
====

В этой же функции инфинитив используется и после слов *the first, the second, ..., the last*. При этом на русский язык он переводится глаголом-сказуемым, время которого зависит от времени глагола `to be` в английском предложении

====
* He was the first to come -> Он пришел первым
* He will be the last to leave -> Он уйдет последним
* He is always the first to be invited -> Его всегда приглашают первым
====

3. Инфинитив входит в состав особых конструкций, называемых инфинитивными оборотами (все обороты строятся по своим собственным схемам)

* Объектный инфинитивный оборот

====
* I want you to remember -> Я хочу, чтобы ты запомнил
* I want you to be remembered -> Я хочу, чтобы тебя запомнили
* I know this big car to be very good -> Я знаю, что эта большая машина очень хорошая
====

При использовании объектного инфинитивного оборота в английских предложениях сказуемое 2 может выражаться глаголами, обозначающими (по группам)

** чувственное восприятие *to see, to hear, to feel, to watch, to observe, to notice*. В этом случае частица `to` перед инфинитивом не ставится

====
* I saw him take a pen out of his pocket -> Я видел, как/что он достал ручку из кармана
* I felt him smoke -> Я чувствовал, что он курит
* We heard our friends come back -> Мы услышали, что вернулись наши друзья
====

NOTE: глаголы *to see, to hear* иногда могут не иметь значения воспринимать зрением/слухом, в этих случаях оборот не используется, а глагол *to feel* может иметь значение *считать/полагать*; в этом случае оборот используется, но инфинитив ставится с частицей `to`

====
* I see that you read this book -> Я вижу (знаю), что вы читали эту книгу
* We heard that you were ill last week -> Мы слышали (знаем), что вы были больны на прошлой неделе
* He felt them to come back soon -> Он чувтвовал, что они скоро вернуться.
====

** мнение/суждение *to think, to know, to believe, to declare, to suppose, to understand, to assume, to consider, to find, to expect, to prove*

====
* They think him to be a good driver -> Они думают (считают), что он хороший водитель
* We know that house to have been built this year -> Мы знаем, что тот дом построили в этом году
* I believe them not to be sleeping now -> Я полагаю, что они сейчас не спят
* You can't expect to learn a foreign language in a week -> Не рассчитывай на то, что иностранный язык можно выучить за неделю
====

NOTE: после глаголов *to consider, to declare, to prove, to find* инфинитив, обозначенный глаголом *to be*, можно опускать

====
* He considers her (to be) a beautiful girl -> Он считает ее красивой девушкой
* They declared him (to be) the winner -> Они объявили его победителем
* We found him (to be) dishonest -> Мы обнаружили, что он нечестный
====

** желание *to want, to wish, to desire, I should, I would, (I'd) like

====
* They want us to come back no Sunday -> Они хотят, чтобы мы вернулись в воскресенье
* I'd like you to call me in the morning -> Мне бы хотелось, чтобы ты позвонил мне утром
====

NOTE: после глаголов, обозначающих мнение, суждение, желание можно использовать оборот *there + to be*; в этом случае слово *there* ставится вместо существительного/местоимения в объектном падеже

====
* Their teacher considers there to be nothing difficult in that task -> Их учитель считает, что в этом задании нет ничего сложного
* I don't want there to be any misunderstanding -> Я хочу, чтобы было полное взаимопонимание
====

** приказание/разрешение/просьба *to allow, to permit, to ask for, to order, to command, to request for (в этом случае используется _Passive Infinitive_*

====
* She allowed the car to be taken away -> Она разрешила, чтобы машину убрали с этого места
* He ordered one more bottle of wine to be brought -> Он припазал, чтобы принесли еще одну бутылку вина

NOTE: после глаголов, обозначающих *приказание/разрешение/просьбу*, ставится также *_Active Infinitive_*; такое построение предложения не является инфинитивным оборотом и не вызывает проблем с переводом

====
* I requested him to help -> Я попросил его помочь
* She asked me to buy some bread -> Она попросила меня купить хлеба
====

*_Active Infinitive_* используется только в тех случаях, когда в предложении указывается лицо, на которое направлено приказание/разрешение/просьба

====
* I requested him to help
* She allowed us to smoke in the room
====

если лицо, на которое направлено приказание/разрешение/просьба, не указывается в предложении, используется *_Passive Infinitive_*

====
* She allowed the car to be taken away
* They asked for the answer to be given immediately
* We request for the money to be transferred before the end of the month
====

* Субъективный инфинитивный оборот

Инфинитив связан с подлежащим и обозначает действие, относящееся к подлежащему, или состояние, в котором находится подлежащее

====
* He is known to come tomorrow -> Известно, что он придет завтра
* She was said to be ill at the moment -> Говорили, что в тот момент она была нездорова
====

На русский язык подобные предложения переводятся с помощью придаточных в такой последовательности: сначала переводим второе сказуемое английского предложения и обозначаем его в виде одного слова с неопределенным значением, которое становится главным предложением в русском языке: подлежащее английского предложения становится подлежащим русского придаточного, а инфинитив - сказуемым; придаточное присоединяется к главному союзами *что* и *как*

Все глаголы, после которых ставится объектный инфинитивный оборот, используются и с субъектным оборотом, но в форме *_Passive_*

С субъектным инфинитивным оборотом используются и другие слова (по группам):

** глаголы, обозначающие сообщение/высказывание *to say, to report, to suppose, to announce*

====
* He is said to have bought a new car -> Говорят, он купил новую машину
* They are supposed to come later -> Полагают, что они придут позже
====

NOTE: глагол *to tell*, близкий по значению к *to say*, не образует субъективного оборота. Сравните:

====
* He was told to help his mother -> Ему сказали помогать матери
* He was said to help his mother -> Говорили, что он помогает матери
====

** глаголы-исключения, выступающие в английском предложении с субъектным оборотом в качестве сказуемого, но стоящие в форме *_Active_*: *to seem, to happen, to appear, to prove, to turn out*

====
* She seems to know this man -> Кажется, она знает этого человека
* She appeared to be beautiful -> Она оказалась красивой
* He turned out not to be a doctor -> Оказалось (вопреки ожиданиям), что он не врач
====

NOTE: с данной группой глаголов возможно использование оборота *there + to be*, где глагол *to be* может иногда опускаться

====
* There seems (to be) no doubt about it -> Кажется, в этом нет никакого сомнения
* There appeared to be noboby who could help them -> Оказалось, что помочь им никто не мог
====

в некоторых случаях глагол *to be* может опускаться после глаголов данной группы и без оборота *there + to be*

====
* The task proved (to be) more difficult than we had thought -> Задача оказалась более сложной, чем мы думали
====

** выражения с глаголом *to be*: *to be likely, to be unlikely, to be sure, to be certain*

====
* They are unlikely to come very soon -> Сомнительно, что они придут очень скоро
* He is sure to know her telephone number -> Он, несомненно, знает номер ее телефона
====

4. Инфинитивный оборот с предлогом *for*

Когда мы говорили в начале этого раздела, что свойства и функции инфинитива в предложении в обоих языках совпадают и потому не вызывают проблем с переводом, мы имели в виду случаи, когда действие, обозначенное инфинитивом, относится к подлежащему или к его дополнению

====
* She is going to do that tomorrow -> Она собирается заняться этим завтра
* They told us to wait here -> Они сказали нам ждать здесь
====

Такие случаи встречаются в английском языке наиболее часто. Но иногда действие, обозначенное инфинитивом, относится к лицу или предмету, не являющемуся ни подлежащим, ни дополнением к нему. Для описания как раз таких ситуаций и используется инфинитивный оборот с предлогом *for*. Схема английского предложения:

существительное/ ... ... for + местоимение + инфинитив ... ... .

Оборот может стоять в предложении в разных местах и переводится на русский язык неопределенной формой глагола или придаточным предложением. При этом инфинитив в обороте выражает действие, которое должно быть выполнено лицом/предметом, обозначенным существительным или местоимением, стоящим после предлога *for*

====
* That was for him to find out -> Выяснить это должен был он
* He waited for her to speak -> Он ждал, пока она заговорит
* He stepped aside for my mother to pass -> Он отошол в сторону, чтобы моя мама смогла пройти
====

5. Независимый инфинитивный оборот

Практически не используется в разговорной речи. Чаще всего встречается в научной/коммерческой/юридической литературе. Во всех случаях оборот ставится в конце предложения и отделяется запятой.

В ангийских предложениях с независимым инфинитивным оборотом существует одновременно как бы два подлежащих (одно - со сказуемым, другое с инфинитивом). При этом действие, обозначенное инфинитивом, является второстепенным по отношению к действию, выраженному сказуемым и, следовательно, существительное/местоимение, относящееся к инфинитиву, является тоже второстепенным предметом. Поэтому независимый инфинитивный оборот обычно переводится на русский язык придаточным предложением, присоединяющимся к главному союзом *при этом* или *причем*, а инфинитив обозначает действие, относящееся к лицу/предмету, после которого он стоит

====
The claims should be forwarded by a registered letter, the text to be written in English -> Претензии высылаются заказным письмом, причем текст должен быть на английском языке
====

:numbered:
= Причастие

Причастие - неличная форма глагола, обладающая свойствами глагола и одновременно свойствами прилагательного и наречия. Иногда причастие может обозначать второстепенное действие, выполняемое существительным, - в этом случае оно отвечает на вопрос *какой?* и служит описательным словом к существительному

====
smoking man
====

иногда может обозначать второстепенное действие, которое как бы сопровождает действие, обозначенное сказуемым предложения, - в этом случае оно отвечает на вопросы обстоятельств *как?/когда?/по какой причине?/при каких обстоятельствах?/при каком условии?* и соответствует русскому деепричастию

====
He was sitting by the window reading a book -> Он сидел у окна, читая книгу
====

В английском языке причастия делятся по своей форме на *Причастие I (Participle I)* и *Причастие II (Participle II)*.

По содержащимся в нем грамматическим признакам Причастие I можно определить еще как причастие настоящего времени *_(Present)_*; причастие действительного залога *_(Active)_*; причастие несовершенного вида (т.е. обозначает незаконченное/продолжающееся действие). Образуется прибавлением к форме *_Infinitive_ -ing* при этом в написании некоторых глаголов происходят изменения, не влияющие на произношение 

Причастие II по содержащимся в нем грамматическим признакам можно определить еще как: причастие прошедшего времени *_(Past)_*; причастие страдательного залога *_(Passive)_*; причастие совершенного виде (т.е. обозначает законченное действие). Делятся по своей форме еще на две группы:

* формы, образованные от правильных глаголов, когда к форме *_Infinitive_* прибавляется в конце *-ed*
* формы, образованные от неправильных глаголов

Причастия II используются в предложении самостоятельно только в одной форме, т.е. в виде одного слова. Во всех других случаях они лишь входят в состав сложных форм Причастия I, обозначая в них смысловую часть.

Причастие I используется в предложении в нескольких различных формах, соответствующих по своему значению формулам сказуемого

[cols="4*"]
|===
|
|Indefinite
|Perfect
|

|Active
|~~~~ing
|having ~~~~
|~ed(3)

|Passive
|being ~~~~ed(3)
|having been ~~~~
|~~ed(3)
|===

NOTE: отсутствуют формы *_(Continuous)_*; *-ing* прибавляется к первому вспомогательному глаголу.

В каждой форме Причастия I заложены уже известные нам признаки описываемой ситуации: залог и характер действия. Отсутствует признак времени, который определяется в предложении следующим образом: формы *_Indefinite (Active/Passive)_* обозначают действие, одновременное с действием, обозначенным сказуемым; формы *_Perfect (Active/Passive)_* - действие, предшествовавшие действию, обозначенному сказуемым

====
* Waiting for her answer they didn't say a word -> Ожидая ее ответа, они не произнесли ни слова
* Being left alone, they didn't know what to do -> Оставшись одни (дословно: будучи оставленными), они не знали, что делать
* Having written the letter, he called us -> Написав письмо, он позвонил нам
* Having been written long ago, the letter looked very old -> Будучи написанным давным-давно, письмо выглядело очень старым
====

NOTE: сложные формы причастий используются только для обозначения сопутствующих действий и никогда не отвечают на вопрос *какой?*

NOTE: причастия, образованные от некоторых глаголов чувственного восприятия и движения: *to see, to hear, to come, to arrive, to take, to turn и др.* могут обозначать действие, предшествующее действию, обозначенному сказуемым, и в форме *_Active Indefinite_*

====
* Hearing his voice she ran to meet him -> Услышав его голос, она побежала встречать его
* Turning slowly she went out of the room -> Медленно повернувшись, она вышла из комнаты
====

причастия в форме *_Active Indefinite_* могут также обозначать действие, совпадающее с моментом речи, независимо от того, в каком времени стоит сказуемое

====
* The woman waiting in the car called you the day before yesterday -> Женщина, ждущая (сейчас) в машине, звонила вам позавчера
* I'll never forget her words sounding in my head like an echo -> Я никогда не забуду ее слова, эхом звучащие (сейчас) в моей голове
====

Причастия I/II описвающие предметы и отвечающие на вопрос *какой?*, всегда состоят из одного слова. При этом они могут занимать место как перед описываемым словом (1), так и после него (2).

1. Причастие I в этом случае переводится на русский язык причастием настоящего времени и показывает, что описываемый предмет сам выполняет действие:

====
* smoking man
* reading boy
====

Причастие II в этом случае переводится на русский язык причастием прошедшего времени и показывает, что действие выполнялось над описываемым предметом

====
* a written letter -> написанное письмо
* the invited people -> приглашенные люди
====

2. Причастия I/II в этом случае могут переводиться на русский язык как причастиями с разными значениями, так и придаточными предложениями

====
* The man sitting at the table is a very good doctor -> Человек, сидящий за столом, очень хороший врач
* The liquid used to clean the windows was very strong -> Жидкость, использовавшаяся для мытья окон, была очень сильнодействующая
* I don't know the girl waiting for you -> Я не знаю девушку, ожидающую тебя
* Will you read the book brought yesterday? -> Ты будешь читать книгу, принесенную вчера?
====

Перед Причастиями I/II, форма которых состоит из одного слова, и которые обозначают сопутствующее действие, могут стоять союзы *when/while/if/unless/though* в своем прямом значении. Подобные случаи переводятся на русский язык по-разному

====
* While reading books you must be attentive -> Читая книги, ты должен быть внимательным
* They will leave, unless stopped -> Если их не остановить, они уйдут
* Any good wine if drunk by little portions is very useful for health -> Любое хорошее вино, если его пить небольшими дозами, очень полезно для здоровья
====

NOTE: *when/while* используются без формы *being* при описании ситуаций с обозначением времени, т.е. в тех случаях, где часть предложения со сказуемым отвечает на вопрос *когда?*

====
* My sister took in many expeditions when/while a student -> Моя сестра много раз ходила в походы (когда?) когда была студенткой
* When/While I was in Stockholm, I learned much about Sweden -> Я узнал много нового о Швеции (когда?) когда был в Стокгольме
====

форма *being* (без *wnen/while*) используется при описании ситуаций, обозначающих причину того, на что указывает сказуемое предложения

====
* Being afraid of strangers, the children didn't go with them -> Испытывая страх перед незнакомыми людьми, дети не пошли с ними (почему?)
* Not being able to help us, she was just sitting and crying -> Будучи не в состоянии помочь нам, она просто сидела и плакала (почему?)
====

=== Причастные обороты

Причастия I/II входят в состав особых конструкций, называемых *причастными оборотами*. В английском языке существует три причастных оборота: объектный причастный оборот, субъектный причастный оборот и независимый причастный оборот. Все обороты строятся по своим собственным схемам

1. *Объектный причастный оборот*

Эта схема полностью совпадает со схемой объектного инфинитивного оборота, только на месте инфинитива стоит причастие (где форма Причастия I обозначает действие как процесс, а форма Причастия II - результат действия; инфинитив в таком же обороте обозначает действие как факт).

====
* He saw his father smoking -> Он видел, как его отец курил
* He considered himself engaged to her -> Он считал, что помолвлен (уже) с нею
====

Объектный причастный оборот используется в предложении после глаголов: *to hear, to feel, to see, to watch, to notice, to find, to consider, to like, to dislike и др.*.

После глаголов *to have* и *to get* в значении *иметь* используются только формы Причастия II и обозначают действие, выполенное не самим подлежащим, но для него/по его заказу кем-то другим. Сравните:

====
* I have a new house built -> Я построил новый дом (в русском языке мы часто говорим так, имея в виду, что на самом деле выполнял для нас кто-то другой)
* I have built a new house -> Я построил новый дом (сам/своими руками)
* She had her hair cut -> Она сделала стрижку (но не сама, а в парикмахерской)
* She has cut her hair -> Она подрезала волосы (сама)
====

NOTE: вопросительная и отрицательная формы глагола *to have* в этом случае строятся с помощью вспомогательного глагола *to do*

====
* Did you have your hair cut? -> Ты сделала стрижку?
* I didn't have the house built -> Я так и не построил дом
====

Формы Причастия II используются иногда в аналогичном значении также после глаголов *to wish, to want*

====
We want/wish it done as fast as possible -> Мы хотим, чтобы это сделали как можно быстрее
====

2. Субъектный причастный оборот

Полностью совпадает со схемой субъектного инфинитивного оборота, только на месте инфинитива стоит Причастие I (Причастие II практически не используется в обороте). Форма Причастия I обозначает действие как процесс (инфинитив в таком же обороте обозначает действие как факт)

====
* They were seen smoking -> Видели, как они курили
* They were seen to smoke -> Видели, что они курят
====

Субъектный причастный оборот используется в основном после следующих глаголов: *to see, to hear, to feel, to watch, to find, to observe и др.*

====
* He was found sleeping -> Его нашли спящим
* They were watched playing cards -> За ними наблюдали в то время, когда они играли в карты
====

3. Независимый причастный оборот

Крайне редко используется в разговорной речи и довольно часто - в научной/коммерческой/юридической литературе

Во всех случаях между оборотом и остальной частью предложения ставится запятая.

В английских предложениях с независимым причастным оборотом существуют одновременно как бы два подлежащих (одно — со сказуемым, другое — с причастием). При этом действие, обозначенное причастием, является второстепенным по отношению к действию, выраженному сказуемым и, следовательно, существительное/местоимение, относящееся к причастию, является тоже второстепенным предметом.

В предложении оборот может занимать место перед подлежащим, после сказуемого или в середине предложения (выделяется запятыми).

В большинстве случаев независимый причастный оборот переводится на русский язык придаточными предложениями

* времени

====
* The party being over, they went home -> Когда вечеринка закончилась, они пошли домой
* The work having been done, they went home -> Они пошли домой после того, как сделали всю работу
====

* причины

====
* It being pretty late, she switched on the light -> Так как было довольно поздно, она включила свет
* We went back home, there being too many people inside the restaurant -> Мы отправились обратно домой, так как в ресторане было слишком много народу
====

* условия

в этом случае обычно используются причастия, образованные от глаголов *to permit, to fail*

====
* Time permitting, we will see you off -> Если позволит время, мы проводим тебя
* Your attempt failing, no one will help us -> Если твоя попытка окажется неудачной, нам никто не поможет
====

* сопутствующих обстоятельств

в этом случае оборот может начинаться предлогом *with* и переводиться на русский язык самостоятельным предложением или придаточным, которое присоединяется к главному союзами *при этом, а и др.*

====
* He was sitting still, with his eyes closed -> Он сидел неподвижно, при этом глаза его были закрыты
* She was reading a book, her hands being on the table -> Она читала книгу. Руки ее лежали на столе
====

NOTE: иногда форма Причастия I, образованная от глагола *to be* в обороте опускается, но легко угадывается

====
Lunch (being) over, we went on reading -> Обед закончился, и мы продолжили чтение
====

NOTE: в письменной речи запятой отделяются и выражения *frankly speaking, generally speaking, strictly speaking* не являющиеся независимыми причастными оборотами, но представляющие собой вводную часть ко всему предложению

====
Frankly speaking, I don't like your wife very much -> Честно говоря, мне не очень нравится твоя жена
====

:numbered:
= Герундий

Такого понятия в русском языке не существует. Герундий - это неличная форма глагола, обладающая свойствами глагола и одновременно свойствами существительного (это очень важно запомнить, чтобы различать в предложенях формы герундия и Причастия I)

Герундий обозначает действие как название процесса и поэтому всегда отвечает на вопросы существительного *(что? с чем? от чего? на чем? для чего? ...)

Герундий образуется прибавлением *-ing* к форме *_Infinitive_* и имеет несколько форм соответствующих по своему значению некоторым формам сказуемого и полностью совпадающих с формами Причастия I

[cols="3*"]
|===
|
|Indefinite
|Perfect

|Active
|~~~~ing
|having ~~~~ed(3)

|Passive
|being ~~~~ed(3)
|having been ~~~~ed(3)
|===

NOTE: отсутствуют формы *_Continuous_* `-ing` прибавляется к первому вспомогательному глаголу

В каждой форме герундия заложены уже известные нам признаки описываемой ситуации: залог и характер действия. Отсутствует признак времени, который определяется в предложении следующим образом: формы *_Indefinite (Active/Passive)_* обозначают действие, одновременное с действием, обозначенным сказуемым (после некоторых глаголов — действие, относящееся к будущему), или действие, не относящееся конкретно ни к какому времени; формы *_Perfect (Active/Passive)_* обозначают действие, предшествовавшее действию, обозначенному сказуемым:

====
* Smoking is bad for healt -> Курение (есть) вредно для здоровья
* She doesn't like being looked at -> Она не любит, когда на нее смотрят
* I called them to say about my having arrived -> Я позвонил им, чтобы сказать о том, что я приехал
* He insists on our coming back -> Он настаивал на том, чтобы мы возвратились
====

В некоторых случаях мы можем перевести герундий на русский язык дословно, обозначив название процесса существительным (smoking -> курение; singing -> пение и т.д.) но очень часто в русском языке это сделать невозможно из-за отсутствия соответствующей формы. Как быть в подобных случаях?

Выше мы уже останавливались на том, что промежуточный, "для себя", этап перевода должен быть дословным. Исходя из этого, я предлагаю такой вариант: на промежуточном этапе используем несуществующие в русском языке формы слов для обозначения процесса (smiling -> улыба-ние / eating -> едение и т.д.), не пропуская их, естественно, дальше своей головы. Пользуясь таким приемом, мы получим совершенно непригодное для нормального русского языка предложение, но смысл описанной по-английски ситуации будет понятен. После этого остается лишь построить окончательный вариант переведенного предложения в соответствии с нормами русского языка.

Простая форма герундия *_(Active Indefinite Gerung)_* переводится на русский язык разными способами, но чаще всего - неопределенной формой глагола или существительным

====
* Reading has not begun yet -> Чтение еще не началось
* He called me before leaving -> Он позвонил мне перед отъездом
* She likes swimming -> Она любит плавать
====

Сложные формы почти всегда переводятся придаточными предложениями, при этом следует обязательно учитывать признаки, заложенные в ту или иную форму

====
* He regretted now having written this letter -> Теперь он сожалел, что (раньше) написал это письмо
* We entered the house without being seen -> Никто не видел, как мы вошли в дом
====

После некоторых глаголов *(to want, to need, to require, to deserve, to be worth)* используется форма *_Active Indefinite Gerund_*, но обозначает действие, направленное на подлежащее

====
* Our children want washing -> Наши дети хотят, чтобы их помыли
* The car needed painting -> Машину нужно было крастить
* They were not worth helping -> Им не стоило помогать
====

При наличии перед герундием предлогов *after/on/upon* обозначается действие, предшествовавшее действию, выраженному сказуемым, но используется форма *_Indefinite Gerund_*

====
* After his coming back she locked the door -> После его возвращения она закрыла дверь на ключ
* On/Upon seeing me he took his hand off the table -> Увидев меня, он убрал руку со стола
====

Если перед герундием стоит местоимение или существительное в притяжательном падеже (иногда существительное в объектном падеже), то герундий обозначает действие, совершаемое предметом, выраженным этим местоимением/существительным. Такие случаи переводятся на русский язык придаточными предложениями, которые присоединяются к главному словами *то, что/тем, что и т.п.*

====
* Do you mind my smoking here? -> Вы не против того, чтобы я курил здесь?
* I didn't know anything about mother's coming back on Sunday -> Я ничего не знал о том, что мама возвращается в воскресенье
* We heard of the house being sold -> Мы слышали о том, что этот дом продан
====

Герундий входит в состав многих сложных существительных, указывая на назначение *(для чего?)* предмета, обозначенного во второй части существительного

====
* dining-room -> столовая
* writing-paper -> писчая бумага
* fishing-boat -> рыбацкая лодка
====

Одной из особенностей английского языка является то, что герундий при обозначении второстепенного действия очень близок к инфинитиву, а поскольку в русском языке существует неопределенная форма глагола, мы предпочитаем при переводе с русского на английский пользоваться именно этой формой, хотя в английском языке в таких случаях не всегда ставится инфинитив, а иногда - вообще только герундий или придаточное предложение

Рассмотрим такие случаи по группам:

=== Наиболее употребительные глаголы, после которых можно использовать как инфинитив, так и герундий

* to begin -> начинать/начать
* to cease -> прекращать/прекратить
* to continue -> продолжать/продолжить
* can/cannot afford -> мочь/не мочь позволить (себе)
* to fear -> бояться
* to forget -> забывать/забыть
* to hate -> ненавидеть
* to intend -> намереваться
* to like -> нравиться
* to dislike -> не нравиться
* to neglect -> пренебрегать/не обращать внимания
* to prefer -> предпочитать/предпочесть
* to propose -> предлагать/делать предложение
* to remember -> помнить
* to start => начинать/начать
* to stop -> прекращать/прекратить/остановиться

====
* They began smoking/to smoke -> Они начали курить
* The plane started going/to go down -> Самолет начал снижаться
* They hate working/to work -> Они ненавидят работу
====

NOTE: после глаголов *to forget, to prefer* герундий обозначает регулярное действие, а инфинитив - одноразовое действие

====
* Don't forget locking the door -> Не забывай закрывать дверь на замок
* I prefer staying at home -> Я предпочитаю оставаться дома
* Don't forget to lock the door -> Не забудь закрыть дверь на замок
* I preferred to stay at home -> Я предпочел остаться дома
====

NOTE: после *can/cannot afford* инфинитив используется со значением *себе*, а герундий - со значением *чтобы кто-то*

====
* I cannot afford to see him again -> Я не могу позволить себе снова увидеть его
* We couldn't afford their seeing him again -> Мы не могли допустить, чтобы они снова увиделись с нами
====

NOTE: после *to remember* инфинитив обозначает *помнить/не забыть что-то сделать*, а герундий обозначает *помнить о том, что какое-то действие было выполнено*

====
* She remembered to buy matches -> Она не забыла (помнила) купить спички
* She remembered buying matches -> Она помнила, что покупала спички
====

NOTE: после *to fear* инфинитив используется со значением *сам*, а герундий со значением *что кто-то*

====
* I fear to go there -> Я боюсь идти туда
* He fears my going there -> Он боится, что я пойду туда
====

NOTE: после *to stop* герундий обозначает *прекратить действие*, а инфинитив имеет значение *остановиться, чтобы выполнить действие*

====
* They stopped smoking -> Они перестали курить
* They stopped to smoke -> Они остановились (чтобы) покурить
====

=== Наиболее употребительные выражения с глаголом *to be*, после которых можно использовать инфинитив (если за выражением не ставится предлог) или герундий (если за выражением стоит предлог)

Речь об использовании герундия или инфинитива в этих случаях идет только при обозначении действий. Эти же выражения с предлогами могут стоять с обозначениями предметов (существительными/местоимениями), а предлоги при этом иногда меняются

* to be afraid (of) -> бояться/быть напуганным

====
* I am afraid to call him/I am afraid of calling him -> Я боюсь ему звонить
* Don't be afraid of me -> Не бойся меня
====

* to be amused (at) -> позабавиться

====
* He was amused to see them together/He was amused at seeing them together -> Его забавляло то, что он видел их вместе
* He was amused at/by that story -> Его позабавил этот рассказ
====

* to be annoyed (at) -> быть раздраженным/раздосадованным

====
* She was annoyed not to be called/She was annoyed at not being called -> Она нервничала из-за того, что ей не звонили
* She was annoyed at/with children -> Она была раздражена из-за детей
====
* to be ashamed (of) -> стыдиться

====
* They were ashamed of being late/They were ashamed to be late -> Им было стыдно из-за того, что они опоздали
* They were ashamed of themselves -> Им было стыдно за самих себя
====
* to be astonished (at/by) -> удивиться/быть удивленным

====
* I was astonished to see him again/I was astonished at seeing him again -> Я был удивлен, что снова вижу его
* I was not astonished at/by the information -> Меня не удивила эта информация
====

* to be careful (in) -> быть внимательным/осторожным и другие

====
* You must be careful to do this/You must be careful in doing this -> Ты должен быть осторожен, делая это
* You must be careful about/of these things -> Ты должен быть осторожен с этими вещами
====

NOTE: в случаях, обозначенных *(!)* инфинитив относится к подлежащему, а герундий - к другому члену предложения, выраженному местоимением/существительным в притяжательном падеже

* (!) to be certain (about/of) -> быть уверенным

====
* They are certain to help us -> Они, несомненно, помогут нам
* We are certain about/of their helping us -> Мы уверены, что они помогут нам
* We are certain of/about this -> Мы уверены в этом
====

* (!) to be content (with) -> быть довольным

====
* She will be content to go there with us -> Она будет довольна, что пойдет туда с нами
* She will be content with our taking her there -> Она будет довольна, что мы возьмем ее с собой
* She will be content with our present -> Она будет довольна нашим подарком
====

* to be determined (in/on/upon) -> твердо решить/быть полным решимости

====
* I'm determined to speak to them -> Я твердо решил поговрить с ними
* She was determined in defending herself -> Она была полна решимости не дать себя в обиду
* They were determined on/upon providing her innocence -> Они твердо решили доказать ее невиновность
====

* to be fortunate (in) -> повезти (с обозначнием предмета практически не используется)

====
I am fortunate to have such a good car/I am fortunate in having such a good car -> Мне повезло, что у меня такая хорошая машина
====

* (!) to be furious (about/over) -> разозлиться/разгневаться

====
* He was furious to see me with her -> Он разгневался, увидев меня с ней
* He was furious about/over their coming late -> Он разгневался из-за того, что они пришли поздно
* He was furious with me -> Он разгневался на меня
====

* (!) to be happy (about) -> быть счастливым/радоваться

====
* She won't be happy to help us -> Ей не доставит много радости помогать нам
* She won't be happy about our leaving -> Ей не доставит много радости то, что мы уезжаем
* Is she happy with her life? -> Она счастлива?
====

* (!) to be keen (on) -> быть в большой степени заинтересованным

====
* I am keen to buy a new house -> Я очень заинтересован в том, чтобы купить новый дом
* I am keen on their buying a new house -> Я очень заинтересован в том, чтобы они купили новый дом
* I'm keen on her -> Я очень заинтересован в ней
====

* to be proud (of) -> гордиться

====
* I am proud to pelp you/I am proud of helping you -> Я горжусь тем, что помогаю тебе
* I am proud of you -> Я горжусь тобой
====

* to be right (in - если о подлежащем/about - если о другом лице) -> оказаться/быть правым

====
* You were right to stay at home/You were right in staying at home -> Ты был прав, что остался дома
* You were right about their staying at home -> Ты был прав - они остались дома
====

* to be scared (of) -> бояться/быть напуганным

====
* She is scared to smoke -> Она боиться курить
* She is scared of coming here -> Она боится приезжать сюда
* Don't be scared of me -> Не пугайся меня
====

* to be selfish (in) -> быть эгоистичным/самонадеянным

====
* He is too selfish to think of that -> Он слишком самонадеян, чтобы думать об этом
* You are selfish in striving for power -> Ты эгоистичен в своем стремлении к власти
* Your husband is selfish in his behaviour towards his sister -> Твой муж ведет себя эгоистично по отношению к своей сестре
====

* to be set -> быть настроенным (against -> против/for -> за)

====
* We are set to leave/We are set for leaving -> Мы настроены уехать
* We are set against leaving -> Мы настроены против того, чтобы уезжать
* We are set for you -> Мы за тебя
====

* to be slow (at/in) -> быть медлительным/медлить (с обозначениме предмета не используется)

====
You are slow to react/You are slow in reacting -> У тебя плохая реакция/Ты медленно реагируешь
====

* to be quick (at) -> быть быстрым

====
* He is quick to understand new rules/He is quick at understanding new rules -> Он быстро понимает/схватывает новые правила
* He is quick about it -> Он быстро справляется с этим
* He is quick with his hands -> Он быстро работает руками
====

* to be sorry (for) -> извиняться

====
* I am sorry to interrupt you -> Извините, что перебиваю вас
* I am sorry to have interrupted you -> Извините, что перебил вас (можете продолжить)
* I am sorry for being late -> Извините, что опоздал
====

* (!) to be sure (of - если о подлежащем/about -> если о другом лице) -> быть уверенным; обязательно/наверняка

====
* He is sure to come -> Он обязательно придет/Я уверен, что он придет
* Are you sure of being invited? -> Ты уверен, что приглашен?
* Are you sure about their being invited? -> Ты уверен, что они приглашены?
====

* to be surprised (at) -> быть удивленным

====
* She was surprised to see me/She was surprised at seeing me -> Она была удивлена, что видит меня
* She was surprised at the news -> Она была удивлена этой новостью
====

* (!) to be touched (at - если о подлежащем/by - если о другом лице) -> быть тронутым/проникнуться чувством

====
* I was touched to find them in the room/I was touched at finding them in the room -> Я был тронут тем, что обнаружил их в комнате
* I was touched by their visiting me -> Я был тронут тем, что они навестили меня
* She was touched by my tears -> Она была тронута моими слезами
====

* (!) to be wrong (in - если о подлежащем/about - если о другом лице) -> ошибаться (противоположно по значению *to be right in/about*)

====
* You were wrong to stay at home/You were wrong in staying at home -> Ты оказался неправ, что остался дома
* You were wrong about their staying at home -> Ты оказался неправ - они не остались дома
* What's wrong with you? -> Что с тобой (случилось)?
====

* (!) еto be pleased (displeased) at/about/by -> быть приятным (неприятным)

====
* I am pleased to meet you -> Приятно с вами познакомиться
* I'm pleased at/about/by your coming -> Мне приятно, что вы пришли
* I am pleased with you -> Ты доставляешь мне удовольствие
====

* to be good (at) -> хорошо (с инфинитивом); быть умелым (с герундием)

====
* It is good to be back at home -> Хорошо снова быть дома
* I am not good at driving -> Я плохо вожу машину
* He is good at/in languages -> Ему хорошо дается изучение языков
====

* to be interested (in) -> быть интересным (с инфинитивом); быть заинтересованным (с герундием)

====
* You will be interested to know that she is here again -> Тебе интересно будет узнать, что она снова здесь
* Are you interested in buying a new house? -> Ты заинтересован в покупке нового дома?
* She is not interested in politics -> Ее не интересует политика
====

* to be grateful (for) -> быть благодарным

====
* He was grateful to be invited/He was grateful for being invited -> Он был благодарен за то, что его пригласили
* He was grateful to me for my help -> Он был благодарен мне за помощь
====

=== Наиболее употребительные выражения с глаголом *to be*, после которых для обозначения второстепенного действия используется только герундий

* to be aware of -> знать/быть осведомленным
* to be busy in -> быть занятым (в)
* to be capable of -> быть способным (на)
* to be fond of -> очень нравиться
* to be guilty of -> быть виноватым (в)
* to be indignant at -> негодовать
* to be sensible of -> чувствовать/понимать
* to be severe in -> быть строгим/суровым
* to be worth -> стоить что-либо сделать

====
* They are aware of our living together -> Они знают о том, что мы живем вместе
* I'm busy in looking for new ideas -> Я занят поиском новых идей
* Are you capable of stopping them? -> Ты способен (на то, чтобы) остановить их?
* She is fond of playing tennis -> Ей очень нравится играть в теннис
* I am not guilty of being late -> Я не виновать в том, что опоздал
* He will be indignant at their leaving so soon -> Он придет в негодование из-за того, что они уезжают так скоро
* She was sensible of having made an awkward mistake -> Она чувствовала/понимала, что допустила оплошность
* Don't be too severe in judging his behaviour -> Не суди его (поведение) слишком строго
* That match was worth seeing -> Этот матч стоило посмотреть
====

=== Наиболее употребительные глаголы, после которых для обозначения второстепенного действия используется только герундий

* to avoid -> избегать/избежать
* to burst out -> разразиться
* to deny -> отрицать
* to enjoy -> наслаждаться/насладиться
* to excuse -> извинять/извинить
* to fancy -> нравиться/представить себе (в восклицаниях)
* to finish -> заканчивать/закончить
* to give up -> прекращать/прекратить
* to go on -> продолжать/продолжить
* to keep (on) -> продолжать
* to mind -> возражать (в вопросах и отрицаниях)
* to postpone -> отложить/перенести на другой срок
* to put off -> отложить/перенести на другой срок
* cannot help -> не удержаться от ...

====
* He avoided looking at us -> Он избегал смотреть на нас
* They burst out laughing -> Они разразились смехом
* She denied going there -> Она отрицала, что ходила туда
* You will enjoy smoking this cigar -> Ты получишь удовольствие от этой сигары
* Excuse my being late -> Прошу извинить меня за опоздание
* We don't fancy doing it -> Нам не нравится заниматься этим
* Just fancy coming there! -> Только представь себе, что мы поедем туда!
* When will you finish working? -> Когда ты закончишь работу?
* He gave up eating in the evening -> Он перестал есть по вечерам
* Go on reading -> Продолжай читать
* She kept (on) driving -> Она продолжала ехать
* Do you mind my helping you? -> Вы не против, если я помогу вам?
* I don't mind your smoking here -> Курите здесь, я не возражаю
* They postponed/put off leaving because of the weather -> Они отложили отъезд из-за погоды
* She couldn't help smiling -> Она не могла сдержать улыбку
====

=== Наиболее употребительные глаголы и выражения в определенном сочетании с предлогами или другими словами, после которых для обозначения второстепенного действия может использоваться только герундий

* to accuse of -> обвинять в том, что ...
* to agree to -> согласиться на то, чтобы ...
* to approve of -> одобрять
* to complain of -> жаловаться на то, что ...
* to depend on/upon -> зависеть от того, ...
* to feel like -> собираться/чувствовать в себе желание сделать что-то
* to look like -> собираться сделать что-то (о ком-либо другом)
* to insist on -> настаивать на том, чтобы ...
* to object to -> возражать против того, чтобы ...
* to persist in -> упорно продолжать заниматься чем-либо
* to prevent from -> удержать от того, чтобы ... /не допустить, чтобы ...
* to rely on/upon -> положиться на то, что ...
* to speak of -> говорить о том, что/чтобы ...
* to succeed in -> добиться успеха в (выполнении какого-либо действия)
* to thank for -> благодарить за то, что ...
* to think of -> думать о том, что/чтобы ...
* to give up the idea of -> отказаться от затеи сделать что-либо
* to look forward to -> с нетерпением ждать выполнения какого-либо действия
* to miss the opportunity -of -> упустить возможность сделать что-либо
* (not) to like the idea of -> (не) нравиться (об идее выполнить какое-либо действие)

====
* They accuse me of helping you -> Они обвиняют меня в том, что я помогаю тебе
* She didn't agree to coming here -> Она не согласилась на то, чтобы прийти сюда
* Father approves of my learning English -> Отец одобряет то, что я учу английский язык
* She never complains of being poor -> Она никогда не жалуется на то, что бедная
* Everything will depend on/upon their coming on time -> Все будет зависеть от того, придут ли они вовремя
* I feel like sleeping -> (Похоже,) Меня клонит ко сну
* She looks like leaving -> (Похоже, что) Она собирается уходить
* They insist on our getting married -> Они настаивают на том, чтобы мы поженились
* Do they object to my leaving him? -> Они возражают против того, чтобы я ушла от него?
* He persisted in asking questions -> Он упорно продолжал задавать вопросы
* Don't prevent me from buying this house -> Я все равно куплю этот дом, не отговаривай меня
* You may rely on/upon my coming back -> Я вернусь, можешь на меня положиться
* I can't speak of our having been seen there -> Я не могу говорить о том, что нас видели там
* He succeeded in learning those rules -> Ему удалось/Он сумел выучить те правила
* How can you suspect me of loving her? -> Как ты можешь подозревать меня в том, что я люблю ее?
* I want to thank you for bringing this letter -> Я хочу поблагодарить тебя за то, что ты принес это письмо
* I often think of your leaving -> Я часто думаю о твоем отъезде 
* They gave up the idea of selling their car -> Они отказались от идеи продать свою машину
* She looks forward to visiting Paris -> Она с нетерпением ждет, когда сможет поехать в Париж
* Don't you like the idea of inviting him to our house? -> Разве тебе не нравится идея о том, чтобы пригласить его в наш дом?
* He won't miss the opportunity of buying several new books -> Он не упустит возможность купить несколько новых книг
====

=== Наиболее употребительные предлоги и предложные сочетания, после которых для обозначения второстепенного действия используется герундий

after/on/upon => после (того, как)
against -> против (того, чтобы)
apart/aside from -> помимо/кроме (того, что)
by -> путем/при помощи
because of -> из-за/по причине (того, что)
besides -> кроме
before -> перед (тем, как)
from -> из/от
for fear of -> из-за опасения (, что)
in -> в (каком-либо занятий)
instead of -> вместо (того, чтобы)
of -> обозначает родительный падеж
owing to -> благодаря (тому, что)/из-за (того, что)
for the purpose of/with the object of/with a view to/with the view of (официальные) -> с целью (того, чтобы)
for the sake of -> ради (того, чтобы)
subject to (официальное) -> в (том) случае, если
through -> из-за/по причине (того, что)
without -> без

====
* They voted against/for accepting the plan -> Они проголосовали против принятия/за принятие этого плана
* Apart/Aside from being too small, the dress doesn't suit me -> Кроме того, что платье слишком мало, оно еще и не идет мне
* By working hard he gained rapid promotion -> Упорно работая, он быстро продвигался по службе
* Because of/Owing to his wife's being there, I said nothing about it -> Я ничего не сказал об этом потому, что там была его жена
* He drank two cups of tea before leaving -> Перед уходом он выпил две чашки чая
* The play was badly acted, besides being far too long -> Актеры играли плохо, а сама пьеса была слишком растянутой
* Wild fruit kept us from dying of starvation -> Дикорастущие фрукты спасли нас от голодной смерти
* We spoke in whispers for fear of waking the baby -> Мы разговаривали шепотом, чтобы не разбудить ребенка
* He's behind the others in reading -> Он отстает от других в чтении
* Let's do something instead of lying here in bed -> Давай лучше займемся каким-нибудь делом, чем валяться в кровати
* Let this accident be an object lesson in the dangers of drinking and driving -> Пусть это происшествие станет наглядным уроком того, как опасно пить за рулем
* We have forwarded your inquiry to our plant for the purposes of/with the object of/with a view to/with the view of finding out whether the machine can be altered according to your specification -> Мы передали Ваш запрос на наш завод с целью выяснить, существует ли возможность внести изменения в конструкцию этого станка согласно Вашей спецификации
* She argues for the sake of arguing -> Она спорит только ради того, чтобы спорить
* This offer is subject to our being able to obtain an export licence -> Мы можем принять это предложение только при условии получения нами лицензии на экспорт
* We missed the plane through being held up on the way -> Мы опоздали на самолет из-за того, что попали в пробку на дороге
* You can't do this without being helped -> Ты не можешь сделать это без чьей-либо/посторонней помощи
====

