= English Book
Doc Writer <vojtehovsky@gmail.com>
2014-12-23
:revnumber: {project-version}
:toc:
:toc-title: Content

:numbered:
== Порядок слов в повествовательном утвердительном предложении

1 место - подлежащее:: Отвечает на вопрос _кто? / что?_. Может иметь описательные слова, которые ставятся перед подлежащим или (реже) после него.
2 место - сказуемое:: Обозначает действие, меняет форму при описании различных ситуаций.
3 место - дополнения:: Обозначают предметы и понятия, с которыми главный член предложения (подлежащее) вступает во взаимодействие; отвечают на вопросы всех падежей, кроме именительного: _кого? / что? / кому? / чему? / кем? / чем? / ..._
4 место - обстоятельства:: Бывают разные: образа действия - _как? / каким образом?_, времени - _когда?_, места - _где?_. Обстаятельств в предложении может быть несколько. В этом случае они располагаются в таком порядке: обстоятельство образа действия, обстоятельство места, обстоятельство времени:

====
Девочка читает книгу медленно в библиотеке каждый день.
====

Если обстоятельство места состоит из большего количетсва слов, чем обстоятельство времени, то его нужно ставить после обстоятельства времени:

====
Девочка читает книгу каждый день в библиотеке городского молодежного центра.
====

Обстоятельства места или времени можно ставить перед подлежащим. Это происходит в тех случаях, когда данное обстоятельство нужно выделить в ситуации:

====
Каждый день девочка читает книгу в библиотеке
====


[cols="5*", options="header"]
|===
|возможно
|1
|2
|3
|4

|обстоятельства времени/места
|подлежащее
|сказуемое
|дополнения
|обстоятельства
|===

:numbered:
== Построение простого английского предложения

В английском языке основную работу по соединению слов в предложении выполняет сказуемое.
При построении любого английского предложения мы должны определить характер действия.

В английском языке существует 7 формул сказуемого и в любом предложении присутствует одна из семи формул.

=== Залог

Active (действительный):: подлежащее (главный член предложения) само выполняет действие

====
Ученики пишут диктант
====

Passive (страдательный):: действие выполняется над подлежащим

====
Диктант пишется учениками
====

=== Характер действия (в русском языке отсутствует)

Indefinite:: сообщение о действии как обычном факте
Continuous:: сообщение о действии, которое в описываемой ситуации требует затраты на себя определенного времени
Perfect:: завершенность действия (не обязательно) + важность сообщения для собеседника + возможность для собеседника воспользоваться сообщением о выполненном действии
Perfect Continuous:: сообщение о действии, происходящем в течение какого-то промежутка времени (промежуток времени указывается или подразумевается)

=== Время

Past:: прошедшее
Present:: настоящее
Future:: будущее

=== Формулы

[cols="2*", options="header"]
|===
|Active
|Passive

|to ???
|to be + ???ed (3-я форма)

|to be + ???ing
|to be being + ???ed (3-я форма)

|to have + ???ed (3-я форма)
|to have been + ???ed (3-я форма)

|to have been + ???ing
|не существует
|===

Все формулы стоят в неопределенной форме (*_Infinitive_*), т.е. отвечают на вопрос _что делать? / что сделать?_.

В формулах глаголы делятся на *смысловые* (стоят последними) и *вспомогательные* (стоят перед смысловыми).
Смысловой глагол берется каждый раз из словаря и строго приобретает вид, заданный ему по формуле.
Вспомогательный глагол, занимающий первое место в формуле (*to be* или *to have*) постоянно изменяет свою форму, показывая таким образом нужное время.
Второй вспомогательный глагол (в тех формулах, где он есть: *been / being*) никак не изменяется и служит лишь для того, чтобы данная формула отличалась от других.

*Запомните*

* все формулы неделимы, т.е. из них нельзя выбросить ни одной детали, кроме частицы `to`; мы должны воспринимать их как одно русское слово;
* в формулу нельзя вводить никакие дополнительные детали, каждая формула уже имеет свой законченный вид;
* любое структурное изменение формулы или ведет к ее распаду или же к какому-то новому образованию, что делает ее одинаково непонятной;
* в каждой формуле уже заложены какие-то признаки описываемых ситуаций, и мы должны понимать их.

:numbered:
== Выбор характера действия

Выбор характера действия - самый сложный момент в анализе английского сказуемого, потому-что в русском языке мы этим не занимаемся.

== Формы вспомогательных глаголов в зависимости от времени, лица и числа


