Вопросительная форма глаголов `to be, to have, can, may, must` образуется путем перестановки: глагол ставится перед
подлежащим. Вопросительная форма остальных глаголов образуется с помощью вспомогательного глагола `to do`, который
ставится перед подлежащим. В вопросительной форме окончание 3-го лица ед. числа `-e(s)` принимает не смысловой, а
вспомогательный глагол:

====
he makes - does he make?
====

Вопросительные слова

* *_who_* - кто?
* *_whom_* - кого? (выходит из употребления и заменяется `who`)
* *_whose_* - чей?
* *_what_* - что? какой?
* *_which_* - который?
* *_where_* - где?
* *_when_* - когда?
* *_why_* - почему?
* *_how_* - как?
* *_how many_* - сколько? (множество отдельных предметов)
* *_how much_* - сколько? (вещество или абстрактное понятие)

Вопросительные предложения могут представлять собой общие вопросы и специальные вопросы. Общими называются такие,
на которые можно ответить "да" или "нет". Специальные вопросы имеют целью выяснение какого-либо факта или
обстоятельства. Начинаются они с вопросительного слова.

В общих вопросах глагол всегда стоит в вопросительной форме. В специальных вопросах глагол стоит в вопросительной
форме только в том случае, если вопросительное слово не является подлежащим или определением подлежащего.

====
Who knows this? +
Whose friend lives in his house? +

What do you know? +
What bridge do you see?
====
