Отрицательная форма глаголов `to be, to have, can, may, must` образуется с помощью отрицания `not`, которое ставится
после глагола.

[cols="5*", options="header"]
|===
|to be
|to have
|can
|may
|must

|I am not
|I have not
|I cannot
|I may not
|I must not

|he (she, it) is not
|he (she, it) has not
|he (she, it) cannot
|
|

|we (you, they) are not
|we (you, they) have not
|we (you, they) cannot
|
|
|===

С глаголом `can` отрицание пишется слитно, а в остальных случаях отдельно

Отрицательная форма смысловых глаголов образуется с помощью вспомогательного глагола `do` и отрицания `not`. Для
образования отрицательной формы глагола нужно поставить вспомогательный глагол `do` и отрицание `not` перед смысловым
глаголом:

====
I do not see +
he does not work
====

По-английски достаточно выразить отрицание один раз. Поэтому в отрицательном по смыслу предложении глагол стоит
в отрицательной форме лишь в том случае, если в предложении нет других отрицательных слов.

====
I do not know him +
He does not live here
====

Если в предложении есть отрицательное слово, то глагол стоит в утвердительной форме:

====
Nobody knows him +
I never go there +
No man can do it
====

Сокращения `isn't`, `aren't`, `doesn't`, `don't`, `haven't`, `hasn't` употребляются в разговорной речи и художественной
литературе
