of:: Предлог `of` обычно выражает отношение принадлежности. Существительно с предлогом `of` обычно переводится на
русский язык существительным в родительском падеже.

====
my friend's children - the children of my friend +
this part of the city +
this side of the river
====

in:: Переводится *в* и встречается в предложениях, отвечающих на вопровы *где, в чем?*

at:: Переводится *в, на, у, при*. Отвечает на вопрос *где?*, но имеет более широкое значение, чем `in`. Если предлог
`in` обычно значит в пределах чего-либо, внутри чего-либо, то `at` опрежеляет местонахождение менее определенно.

on:: Обычно переводится *на* и встречается в предложениях, указывающих, на чем находится предмет или на что его надо
поместить

to:: Передает направление движения и обычно переводится *в* или *к*, а иногда *на*. Он часто встречается в
предложениях, отвечающих на вопрос *куда?*

from:: Обычно переводится *от*, *из*, а иногда *с*

into:: Означает движение внутрь чего-либо и обычно переводится предлогом в (на вопрос *куда? во что?*)
